// Agency Group — CEO Command Center
// app/control-tower/ceo/page.tsx
// Executive overview: Revenue Intelligence, AI ROI, Conversion Funnel, Alerts
// RSC page — no 'use client'

import Link from 'next/link'
import { Suspense } from 'react'
import { supabaseAdmin } from '@/lib/supabase'
import type { GovernanceStatusResponse } from '@/app/api/control-tower/governance-status/route'

export const revalidate = 60 // ISR 60s

// ─── Types ────────────────────────────────────────────────────────────────────

interface AIDecisionsSummary {
  total: number
  fallback_count: number
  error_count: number
  avg_latency_ms: number
}

interface ChartDataPoint {
  month: string
  value: number
}

interface IncidentRow {
  title: string
  severity: string
  detected_at: string
  status?: string
}

// No static fallbacks — if no real data exists return empty array

// ─── Data Fetchers ────────────────────────────────────────────────────────────

async function fetchAIDecisionsCount(): Promise<number> {
  try {
    const baseUrl = process.env.INTERNAL_API_BASE ?? 'http://localhost:3000'
    const token = process.env.INTERNAL_API_TOKEN ?? process.env.CRON_SECRET ?? ''
    const res = await fetch(`${baseUrl}/api/control-tower/ai-decisions`, {
      headers: { Authorization: `Bearer ${token}` },
      next: { revalidate: 60 },
    })
    if (!res.ok) return 0
    const data = (await res.json()) as { summary?: AIDecisionsSummary }
    return data?.summary?.total ?? 0
  } catch {
    return 0
  }
}

// Canonical closed stages — must match kpi-snapshot, businessPrimitiveEngine, revenueAttribution
const CEO_CLOSED_STAGES = ['post_sale', 'escritura', 'escritura_sell', 'Escritura', 'Escritura Concluída']

async function fetchPipelineValue(): Promise<string> {
  try {
    const sb = supabaseAdmin as unknown as { from: (t: string) => unknown }
    // PIPELINE FIX: was .not('fase','in','(perdido,cancelado)') — incomplete exclusion.
    // Closed stages (CPCV/Escritura) would inflate pipeline as deals accumulated.
    // Now uses canonical CLOSED_STAGES list consistent with kpi-snapshot cron.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error } = await (sb.from('deals') as any)
      .select('deal_value, fase')
    if (error || !data) return '—'
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const total: number = (data as any[])
      .filter((row: any) => !CEO_CLOSED_STAGES.includes(row.fase ?? ''))
      .reduce((sum: number, row: any) => {
        const v = typeof row.deal_value === 'number' ? row.deal_value : Number(row.deal_value ?? 0)
        return sum + (isNaN(v) ? 0 : v)
      }, 0)
    if (total === 0) return '—'
    const millions = total / 1_000_000
    return `€${millions.toFixed(1)}M`
  } catch {
    return '—'
  }
}

async function fetchAIROI(): Promise<string> {
  try {
    const sb = supabaseAdmin as unknown as { from: (t: string) => unknown }
    const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { count: aiCount, error: aiError } = await (sb.from('ai_audit_log') as any)
      .select('id', { count: 'exact', head: true })
      .eq('action', 'ai:execute')
      .gte('created_at', since)

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { count: dealCount, error: dealError } = await (sb.from('learning_events') as any)
      .select('id', { count: 'exact', head: true })
      .eq('event_type', 'deal_closed')
      .gte('created_at', since)

    if (aiError && dealError) return '—'

    const executions = typeof aiCount === 'number' ? aiCount : 0
    const closedDeals = typeof dealCount === 'number' ? dealCount : 0

    if (executions === 0) return '—'
    // AI ROI = commission revenue generated by AI-assisted deals / AI execution cost
    // avg commission per closed deal (configurable; default conservative for PT luxury market)
    const avg_commission = Number(process.env.ORG_AVG_COMMISSION_EUR ?? '25000')
    // AI cost per execution — configurable via ORG_AI_COST_PER_EXEC_EUR (default €0.03)
    const ai_cost_per_exec = Number(process.env.ORG_AI_COST_PER_EXEC_EUR ?? '0.03')
    const roi_revenue = closedDeals * avg_commission
    const roi_cost    = executions * ai_cost_per_exec
    const multiplier  = roi_cost > 0 ? roi_revenue / roi_cost : 0
    if (multiplier === 0) return '—'
    return `${multiplier.toFixed(0)}×`
  } catch {
    return '—'
  }
}

async function fetchConversionRate(): Promise<string> {
  try {
    const sb = supabaseAdmin as unknown as { from: (t: string) => unknown }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { count: contactCount, error: cError } = await (sb.from('contacts') as any)
      .select('id', { count: 'exact', head: true })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { count: dealCount, error: dError } = await (sb.from('deals') as any)
      .select('id', { count: 'exact', head: true })

    if (cError || dError) return '—'

    const contacts = typeof contactCount === 'number' ? contactCount : 0
    const deals = typeof dealCount === 'number' ? dealCount : 0

    if (contacts === 0) return '—'
    const rate = (deals / contacts) * 100
    return `${rate.toFixed(1)}%`
  } catch {
    return '—'
  }
}

async function fetchActiveTenants(): Promise<string> {
  try {
    const sb = supabaseAdmin as unknown as { from: (t: string) => unknown }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { count, error } = await (sb.from('tenants') as any)
      .select('id', { count: 'exact', head: true })
    // Table may not exist yet — return '—' rather than the fake hardcoded '1'
    if (error) return '—'
    if (typeof count !== 'number') return '—'
    return String(count)
  } catch {
    return '—'
  }
}

async function fetchGovernanceStatus(): Promise<GovernanceStatusResponse | null> {
  try {
    const baseUrl = process.env.INTERNAL_API_BASE ?? 'http://localhost:3000'
    const token   = process.env.INTERNAL_API_TOKEN ?? process.env.CRON_SECRET ?? ''
    const res = await fetch(`${baseUrl}/api/control-tower/governance-status`, {
      headers: { Authorization: `Bearer ${token}` },
      next: { revalidate: 60 },
    })
    if (!res.ok) return null
    return res.json() as Promise<GovernanceStatusResponse>
  } catch {
    return null
  }
}

async function fetchChartData(): Promise<ChartDataPoint[]> {
  try {
    const sb = supabaseAdmin as unknown as { from: (t: string) => unknown }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error } = await (sb.from('kpi_snapshots') as any)
      .select('snapshot_date, pipeline_value')
      .order('snapshot_date', { ascending: true })
      .limit(12)

    if (error || !data) return []

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const rows = data as any[]
    if (rows.length === 0) return []

    // Group by month (YYYY-MM), take last 6
    const byMonth: Record<string, number> = {}
    for (const row of rows) {
      if (!row.snapshot_date) continue
      const d = new Date(row.snapshot_date as string)
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
      const v = typeof row.pipeline_value === 'number'
        ? row.pipeline_value
        : parseFloat(row.pipeline_value ?? '0')
      if (!isNaN(v)) {
        byMonth[key] = (byMonth[key] ?? 0) + v
      }
    }

    const PT_MONTHS = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']

    const sorted = Object.entries(byMonth)
      .sort(([a], [b]) => a.localeCompare(b))
      .slice(-6)
      .map(([key, total]) => {
        const monthIdx = parseInt(key.split('-')[1], 10) - 1
        return {
          month: PT_MONTHS[monthIdx] ?? key,
          value: parseFloat((total / 1_000_000).toFixed(2)),
        }
      })

    return sorted
  } catch {
    return []
  }
}

async function fetchTopAlerts(): Promise<IncidentRow[]> {
  try {
    const sb = supabaseAdmin as unknown as { from: (t: string) => unknown }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error } = await (sb.from('incidents') as any)
      .select('title, severity, detected_at, status')
      .in('status', ['open', 'investigating'])
      .order('detected_at', { ascending: false })
      .limit(3)

    if (error || !data) return []
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (data as any[]).filter((r: any) => r.title)
  } catch {
    return []
  }
}

// ─── Sub-components ───────────────────────────────────────────────────────────

// dataState distinguishes WHY a value is '—':
//   'ok'    — has real data, display normally
//   'empty' — query succeeded, 0 rows (gray, "No data yet")
//   'error' — query failed (red, "Query failed")
//   'stale' — last updated >24h ago (yellow, message passed via trend)
type DataState = 'ok' | 'empty' | 'error' | 'stale'

function StatCard({
  label,
  value,
  trend,
  trendDir,
  color,
  dataState = 'ok',
}: {
  label: string
  value: string
  trend?: string
  trendDir?: 'up' | 'down' | 'neutral'
  color?: 'green' | 'blue' | 'amber' | 'purple' | 'default'
  dataState?: DataState
}) {
  // Override colors when data is degraded
  const isOk = dataState === 'ok'

  const valueColor = !isOk
    ? dataState === 'error' ? 'text-red-400'    :
      dataState === 'stale' ? 'text-amber-400'  :
      'text-slate-500'   // empty → gray
    : color === 'green'  ? 'text-green-400'  :
      color === 'blue'   ? 'text-blue-400'   :
      color === 'amber'  ? 'text-amber-400'  :
      color === 'purple' ? 'text-purple-400' :
      'text-slate-100'

  const trendColor =
    !isOk             ? (dataState === 'error' ? 'text-red-400' : dataState === 'stale' ? 'text-amber-400' : 'text-slate-500') :
    trendDir === 'up'   ? 'text-green-400' :
    trendDir === 'down' ? 'text-red-400'   :
    'text-slate-400'

  const trendIcon =
    !isOk             ? (dataState === 'error' ? '✗' : dataState === 'stale' ? '⚠' : '○') :
    trendDir === 'up'   ? '↑' :
    trendDir === 'down' ? '↓' :
    '→'

  const stateTrend =
    dataState === 'empty' ? 'No data — system not yet operational' :
    dataState === 'error' ? 'Query failed — check DB connection'   :
    undefined

  const displayTrend = stateTrend ?? trend

  // Border color hint for degraded states
  const borderClass =
    dataState === 'error' ? 'border-red-900/50'   :
    dataState === 'stale' ? 'border-amber-900/50' :
    'border-slate-800'

  return (
    <div className={`bg-[#111118] border ${borderClass} rounded-lg p-4 flex flex-col gap-1 min-w-0`}>
      <p className="text-xs text-slate-500 uppercase tracking-widest font-medium truncate">{label}</p>
      <p className={`text-3xl font-bold leading-none ${valueColor}`}>{value}</p>
      {displayTrend && (
        <div className="flex items-center gap-1 mt-1">
          <span className={`text-xs font-mono ${trendColor}`}>{trendIcon} {displayTrend}</span>
        </div>
      )}
    </div>
  )
}

function StatusRow({
  label,
  status,
  dot,
  detail,
}: {
  label: string
  status: string
  dot: 'green' | 'amber' | 'red' | 'blue' | 'gray' | 'orange'
  detail?: string
}) {
  const dotColor =
    dot === 'green'  ? 'bg-green-400'  :
    dot === 'amber'  ? 'bg-amber-400'  :
    dot === 'orange' ? 'bg-orange-400' :
    dot === 'red'    ? 'bg-red-400'    :
    dot === 'gray'   ? 'bg-slate-500'  :
    'bg-blue-400'

  return (
    <div className="flex items-start justify-between py-2 border-b border-slate-800 last:border-0 gap-2">
      <span className="text-sm text-slate-300 flex-shrink-0">{label}</span>
      <div className="flex flex-col items-end gap-0.5">
        <div className="flex items-center gap-2">
          <span className={`w-2 h-2 rounded-full flex-shrink-0 ${dotColor}`} />
          <span className="text-xs text-slate-400 font-mono">{status}</span>
        </div>
        {detail && <span className="text-[10px] text-slate-600 font-mono text-right max-w-[180px] truncate">{detail}</span>}
      </div>
    </div>
  )
}

function AlertCard({
  severity,
  message,
  timestamp,
}: {
  severity: 'warning' | 'success' | 'info'
  message: string
  timestamp: string
}) {
  const borderColor =
    severity === 'warning' ? 'border-amber-600/50' :
    severity === 'success' ? 'border-green-600/50'  :
    'border-blue-600/50'

  const bgColor =
    severity === 'warning' ? 'bg-amber-950/30' :
    severity === 'success' ? 'bg-green-950/30'  :
    'bg-blue-950/30'

  const icon =
    severity === 'warning' ? '🟡' :
    severity === 'success' ? '🟢' :
    '🔵'

  return (
    <div className={`${bgColor} border ${borderColor} rounded-lg p-3 flex items-start gap-3`}>
      <span className="text-lg leading-none mt-0.5">{icon}</span>
      <div className="flex-1 min-w-0">
        <p className="text-sm text-slate-200 leading-snug">{message}</p>
        <p className="text-xs text-slate-500 mt-1 font-mono">{timestamp}</p>
      </div>
    </div>
  )
}

// ─── Revenue Bar Chart (HTML/CSS — no external lib) ──────────────────────────

function RevenueBarChart({ data }: { data: ChartDataPoint[] }) {
  if (data.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-32 gap-2">
        <p className="text-slate-500 text-sm">No KPI snapshots yet</p>
        <p className="text-slate-600 text-xs font-mono">Run the KPI cron to populate kpi_snapshots</p>
      </div>
    )
  }
  const maxValue = Math.max(...data.map(d => d.value), 0.01)
  return (
    <div className="flex flex-col gap-3">
      {/* Bars */}
      <div className="flex items-end gap-2 h-32">
        {data.map(d => {
          const heightPct = (d.value / maxValue) * 100
          return (
            <div key={d.month} className="flex-1 flex flex-col items-center gap-1">
              <span className="text-xs text-slate-400 font-mono">€{d.value}M</span>
              <div
                className="w-full bg-blue-600 rounded-t"
                style={{ height: `${heightPct}%` }}
              />
            </div>
          )
        })}
      </div>
      {/* Month labels */}
      <div className="flex gap-2">
        {data.map(d => (
          <div key={d.month} className="flex-1 text-center">
            <span className="text-xs text-slate-500 font-mono">{d.month}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ─── Skeleton ─────────────────────────────────────────────────────────────────

function CEOSkeleton() {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-4 gap-4">
        {[...Array(4)].map((_, i) => (
          <div key={i} className="h-24 bg-[#1A1A24] rounded-lg border border-slate-800 animate-pulse" />
        ))}
      </div>
      <div className="grid grid-cols-10 gap-4">
        <div className="col-span-6 h-52 bg-[#1A1A24] rounded-lg border border-slate-800 animate-pulse" />
        <div className="col-span-4 h-52 bg-[#1A1A24] rounded-lg border border-slate-800 animate-pulse" />
      </div>
      <div className="h-40 bg-[#1A1A24] rounded-lg border border-slate-800 animate-pulse" />
    </div>
  )
}

// ─── Dynamic content ──────────────────────────────────────────────────────────

// ─── Dot color helpers for governance ─────────────────────────────────────────

function govDot(status: string): 'green' | 'amber' | 'orange' | 'red' | 'gray' | 'blue' {
  if (status === 'ACTIVE' || status === 'LIVE' || status === 'HEALTHY' || status === 'READY') return 'green'
  if (status === 'IDLE' || status === 'EMPTY') return 'amber'
  if (status === 'OPEN') return 'orange'
  if (status === 'UNAVAILABLE' || status === 'ERROR') return 'red'
  return 'gray'
}

async function CEOContent() {
  const [
    aiDecisionsResult,
    pipelineResult,
    aiROIResult,
    conversionResult,
    tenantsResult,
    chartResult,
    alertsResult,
    governanceResult,
  ] = await Promise.allSettled([
    fetchAIDecisionsCount(),
    fetchPipelineValue(),
    fetchAIROI(),
    fetchConversionRate(),
    fetchActiveTenants(),
    fetchChartData(),
    fetchTopAlerts(),
    fetchGovernanceStatus(),
  ])

  const aiDecisionsToday = aiDecisionsResult.status === 'fulfilled' ? aiDecisionsResult.value : 0
  const pipelineValue    = pipelineResult.status    === 'fulfilled' ? pipelineResult.value    : '—'
  const aiROI            = aiROIResult.status        === 'fulfilled' ? aiROIResult.value        : '—'
  const conversionRate   = conversionResult.status   === 'fulfilled' ? conversionResult.value   : '—'
  const activeTenants    = tenantsResult.status      === 'fulfilled' ? tenantsResult.value      : '—'
  const chartData        = chartResult.status        === 'fulfilled' ? chartResult.value        : []
  const incidents        = alertsResult.status       === 'fulfilled' ? alertsResult.value       : []
  const governance       = governanceResult.status   === 'fulfilled' ? governanceResult.value   : null

  // Revenue target — read from env, never hardcoded
  const targetEur  = process.env.REVENUE_TARGET_EUR  ? parseInt(process.env.REVENUE_TARGET_EUR, 10)  : null
  const targetDate = process.env.REVENUE_TARGET_DATE ?? null
  const targetLabel = targetEur && targetDate
    ? `Target: €${(targetEur / 1_000_000).toFixed(1)}M by ${new Date(targetDate).toLocaleDateString('pt-PT', { month: 'short', year: 'numeric' })}`
    : 'No revenue target set'

  // Map incidents to AlertCard severity
  function incidentSeverity(row: IncidentRow): 'warning' | 'success' | 'info' {
    const s = (row.severity ?? '').toLowerCase()
    if (s === 'p0' || s === 'p1' || s === 'critical' || s === 'high') return 'warning'
    if (s === 'resolved') return 'success'
    return 'info'
  }

  function formatTimestamp(iso: string): string {
    try {
      return new Date(iso).toLocaleString('pt-PT', {
        day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit',
      })
    } catch {
      return iso
    }
  }

  const useStaticAlerts = incidents.length === 0

  // Derive dataState for each card
  const pipelineState: DataState  = pipelineResult.status  === 'rejected' ? 'error' : pipelineValue  === '—' ? 'empty' : 'ok'
  const aiROIState: DataState     = aiROIResult.status     === 'rejected' ? 'error' : aiROI          === '—' ? 'empty' : 'ok'
  const conversionState: DataState= conversionResult.status === 'rejected' ? 'error' : conversionRate === '—' ? 'empty' : 'ok'
  const tenantsState: DataState   = tenantsResult.status   === 'rejected' ? 'error' : activeTenants  === '—' ? 'empty' : 'ok'

  return (
    <>
      {/* TOP METRICS ROW */}
      <div className="grid grid-cols-4 gap-4">
        <StatCard
          label="Pipeline Value"
          value={pipelineValue}
          trend="Active deals · not closed_lost"
          trendDir={pipelineState === 'ok' ? 'up' : 'neutral'}
          color="green"
          dataState={pipelineState}
        />
        <StatCard
          label="AI ROI"
          value={aiROI}
          trend="Est. revenue / token cost"
          trendDir={aiROIState === 'ok' ? 'up' : 'neutral'}
          color="blue"
          dataState={aiROIState}
        />
        <StatCard
          label="Conversion Rate"
          value={conversionRate}
          trend="Lead → Deal"
          trendDir="neutral"
          color="amber"
          dataState={conversionState}
        />
        <StatCard
          label="Active Tenants"
          value={activeTenants}
          trend={tenantsState === 'empty' ? undefined : 'Agency Group Portugal'}
          trendDir="neutral"
          color="purple"
          dataState={tenantsState}
        />
      </div>

      {/* REVENUE FORECAST + AI GOVERNANCE */}
      <div className="grid grid-cols-10 gap-4">

        {/* Revenue Forecast — 60% */}
        <div className="col-span-6 bg-[#111118] border border-slate-800 rounded-lg p-5">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className="text-sm font-semibold text-slate-200">AI-Projected Revenue Pipeline</h2>
              <p className="text-xs text-slate-500 mt-0.5">6-month forecast · Values in millions EUR</p>
            </div>
            <span className="text-xs bg-blue-900/40 border border-blue-700/40 text-blue-300 px-2 py-0.5 rounded font-mono">
              FORECAST
            </span>
          </div>
          <RevenueBarChart data={chartData} />
          <div className="mt-3 flex items-center gap-4">
            <div className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded bg-blue-600" />
              <span className="text-xs text-slate-500">Projected pipeline</span>
            </div>
            <span className="text-xs text-slate-600 font-mono">{targetLabel}</span>
          </div>
        </div>

        {/* AI Governance Summary — 40% */}
        <div className="col-span-4 bg-[#111118] border border-slate-800 rounded-lg p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-semibold text-slate-200">AI Governance</h2>
            {!governance && (
              <span className="text-[10px] text-slate-500 font-mono">fetch failed</span>
            )}
          </div>
          <div className="space-y-0">
            <StatusRow
              label="Policy Engine"
              status={governance?.policyEngine.status ?? 'UNKNOWN'}
              dot={govDot(governance?.policyEngine.status ?? 'UNKNOWN')}
              detail={governance?.policyEngine.detail}
            />
            <StatusRow
              label="Budget Governor"
              status={governance?.budgetGovernor.status ?? 'UNKNOWN'}
              dot={govDot(governance?.budgetGovernor.status ?? 'UNKNOWN')}
              detail={governance?.budgetGovernor.detail}
            />
            <StatusRow
              label="AI Decisions (24h)"
              status={String(aiDecisionsToday > 0 ? aiDecisionsToday : '—')}
              dot={aiDecisionsToday > 0 ? 'blue' : 'gray'}
            />
            <StatusRow
              label="Circuit Breakers"
              status={
                governance?.circuitBreakers.status === 'HEALTHY'
                  ? 'All Healthy'
                  : governance?.circuitBreakers.status === 'OPEN'
                    ? `${governance.circuitBreakers.openCircuits} OPEN`
                    : governance?.circuitBreakers.status ?? 'UNKNOWN'
              }
              dot={govDot(governance?.circuitBreakers.status ?? 'UNKNOWN')}
              detail={governance?.circuitBreakers.detail}
            />
            <StatusRow
              label="Audit Log"
              status={governance?.auditLog.status ?? 'UNKNOWN'}
              dot={govDot(governance?.auditLog.status ?? 'UNKNOWN')}
              detail={governance?.auditLog.detail}
            />
            <StatusRow
              label="Replay Engine"
              status={governance?.replayEngine.status ?? 'UNKNOWN'}
              dot={govDot(governance?.replayEngine.status ?? 'UNKNOWN')}
              detail={governance?.replayEngine.detail}
            />
          </div>
          <div className="mt-4 pt-3 border-t border-slate-800">
            <p className="text-xs text-slate-500">
              {governance
                ? `Checked ${new Date(governance.computed_at).toLocaleTimeString('pt-PT', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}`
                : 'Governance API unavailable'}
            </p>
          </div>
        </div>
      </div>

      {/* TOP ALERTS */}
      <div className="bg-[#111118] border border-slate-800 rounded-lg p-5">
        <h2 className="text-sm font-semibold text-slate-200 mb-4">Top Alerts</h2>
        <div className="grid grid-cols-1 gap-3">
          {useStaticAlerts ? (
            <div className="text-center py-6 text-slate-500 text-sm">
              Sem alertas activos — todos os sistemas operacionais
            </div>
          ) : (
            incidents.map((inc, idx) => (
              <AlertCard
                key={idx}
                severity={incidentSeverity(inc)}
                message={inc.title}
                timestamp={formatTimestamp(inc.detected_at)}
              />
            ))
          )}
        </div>
      </div>

      {/* NAVIGATION */}
      <div className="flex items-center gap-3 pt-2">
        <Link
          href="/control-tower"
          className="px-4 py-1.5 rounded-full bg-slate-800 hover:bg-slate-700 text-slate-300 text-sm font-medium transition-colors"
        >
          System Overview
        </Link>
        <Link
          href="/control-tower/dashboard"
          className="px-4 py-1.5 rounded-full bg-slate-800 hover:bg-slate-700 text-slate-300 text-sm font-medium transition-colors"
        >
          Live Dashboard
        </Link>
        <Link
          href="/control-tower/ceo"
          className="px-4 py-1.5 rounded-full bg-blue-700 hover:bg-blue-600 text-white text-sm font-medium transition-colors"
        >
          CEO Command Center
        </Link>
      </div>
    </>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function CEOCommandCenterPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-slate-100 p-6 space-y-6">
      {/* Static header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-slate-100">CEO Command Center</h1>
          <p className="text-xs text-slate-500 mt-0.5 font-mono">
            Agency Group · AMI 22506 · Executive Intelligence Dashboard
          </p>
        </div>
        <span className="text-xs text-slate-600 font-mono">ISR 60s</span>
      </div>
      <Suspense fallback={<CEOSkeleton />}>
        <CEOContent />
      </Suspense>
    </div>
  )
}
