export interface Section {
  type: 'intro' | 'h2' | 'h3' | 'p' | 'ul' | 'table' | 'highlight' | 'cta'
  text?: string
  items?: string[]
  headers?: string[]
  rows?: string[][]
  label?: string
}

export interface Article {
  slug: string
  title: string
  description: string
  category: string
  date: string
  author: string
  readingTime: number
  zona?: string
  keywords: string[]
  content: Section[]
}

export const ARTICLES: Article[] = [
  // ─────────────────────────────────────────────
  // ZONA GUIDES (8)
  // ─────────────────────────────────────────────
  {
    slug: 'comprar-casa-lisboa-guia-completo',
    title: 'Comprar Casa em Lisboa: Guia Completo 2026',
    description: 'Tudo o que precisa de saber para comprar imóvel em Lisboa em 2026: bairros, preços, processo legal, IMT e financiamento.',
    category: 'Guias de Compra',
    date: '2026-01-15',
    author: 'Agency Group',
    readingTime: 12,
    zona: 'Lisboa',
    keywords: ['comprar casa lisboa', 'imóveis lisboa 2026', 'preço metro quadrado lisboa'],
    content: [
      { type: 'intro', text: 'Lisboa é hoje um dos mercados imobiliários mais dinâmicos da Europa. Com valorização acumulada superior a 180% na última década e procura internacional crescente, comprar casa em Lisboa em 2026 exige preparação rigorosa — e a escolha certa do bairro pode valer centenas de milhares de euros.' },
      { type: 'h2', text: 'Preços por Bairro em 2026' },
      { type: 'table', headers: ['Bairro', 'Preço Médio €/m²', 'Variação Anual', 'Perfil Comprador'], rows: [['Chiado / Príncipe Real', '€8.200–€12.000', '+14%', 'Internacional HNWI'], ['Alfama / Mouraria', '€6.500–€9.000', '+11%', 'Nacional + Expat'], ['Avenida da Liberdade', '€9.500–€14.000', '+16%', 'Family office / Fundo'], ['Campo de Ourique', '€5.800–€7.500', '+9%', 'Nacional classe média-alta'], ['Belém / Restelo', '€5.200–€7.000', '+8%', 'Família nacional'], ['Parque das Nações', '€4.800–€6.800', '+12%', 'Tech + Expat'], ['Lapa / Santos', '€6.000–€8.500', '+10%', 'Diplomata + Estrangeiro']] },
      { type: 'h2', text: 'Processo de Compra Passo a Passo' },
      { type: 'ul', items: ['Due diligence: certidão predial, caderneta, licença habitação, ónus e encargos', 'CPCV: contrato promessa com 10–30% de sinal. Mora do vendedor = sinal em dobro', 'Financiamento: aprovação prévia recomendada antes de qualquer proposta', 'IMT + IS: 6,5–8,7% sobre valor de compra (imóvel urbano acima de €1M)', 'Escritura: escritura pública + registo na Conservatória do Registo Predial', 'Registo: 1–3 dias úteis com serviço urgente (€150 extra)'] },
      { type: 'h2', text: 'IMT e Impostos na Compra' },
      { type: 'p', text: 'Para imóveis acima de €1.050.400, a taxa de IMT é de 7,5%. Adicione o Imposto de Selo de 0,8% sobre o valor da escritura e 0,6% sobre o montante do empréstimo hipotecário. Em 2026, Lisboa mantém a taxa municipal de IMI entre 0,3% e 0,45% por ano.' },
      { type: 'highlight', label: 'Exemplo Prático', text: 'Apartamento Príncipe Real €1.800.000: IMT €135.000 + IS €14.400 + Notário €2.200 + Registo €800 = Total de impostos e custos: ~€152.400 (8,5% do preço).' },
      { type: 'h2', text: 'Financiamento Hipotecário em Lisboa' },
      { type: 'p', text: 'Os bancos portugueses financiam até 80% para residentes e 70% para não residentes. Com a Euribor a 12 meses em 2,1% (março 2026) e spreads médios de 0,9%, a TAN efectiva ronda 3,1%–3,4% para perfis prime. Prazo máximo: 40 anos (limite de 75 anos à data de fim).' },
      { type: 'h2', text: 'Bairros em Ascensão em 2026' },
      { type: 'ul', items: ['Mouraria: valorização acelerada por regeneração urbana e turismo cultural', 'Marvila: zona industrial reconvertida — hubs criativos e residencial premium', 'Beato: reabilitação intensiva, preços ainda 25–30% abaixo de Alfama', 'Alcântara: proximidade ao rio e Metro — grande potencial de mais-valia 3–5 anos'] },
      { type: 'cta', text: 'Quer uma avaliação gratuita do imóvel que está a considerar em Lisboa? O nosso AVM proprietário cruza 47 variáveis de mercado e entrega resultado em 60 segundos.' },
    ],
  },
  {
    slug: 'comprar-casa-cascais-guia',
    title: 'Cascais & Estoril: O Guia Definitivo para Compradores 2026',
    description: 'Comprar casa em Cascais em 2026: bairros, preços, vantagens fiscais, estilo de vida e o mercado de luxo da Linha de Cascais.',
    category: 'Guias de Compra',
    date: '2026-01-22',
    author: 'Agency Group',
    readingTime: 10,
    zona: 'Cascais',
    keywords: ['comprar casa cascais', 'imóveis cascais 2026', 'linha de cascais preços'],
    content: [
      { type: 'intro', text: 'A 30 minutos de Lisboa e a 10 minutos do Oceano Atlântico, Cascais combina estilo de vida europeu de elite com infra-estrutura internacional — escolas bilingues, campo de golfe de topo, marina e comunidade de expats consolidada. Em 2026, o preço médio situa-se em €4.713/m², mas os prime addresses superam €8.000/m².' },
      { type: 'h2', text: 'Microzonas e Preços' },
      { type: 'table', headers: ['Micromercado', 'Preço €/m²', 'Perfil Predominante'], rows: [['Quinta da Marinha', '€6.500–€10.000', 'HNWI internacional, golfe'], ['Cascais Village / Centro', '€5.500–€8.000', 'Família DINK, expat'], ['Estoril', '€4.800–€7.500', 'Família clássica, diplomata'], ['Birre / Areia', '€3.800–€5.500', 'Familiar nacional'], ['Alcabideche / Malveira', '€2.800–€3.800', 'Primeira compra, custo-vida']] },
      { type: 'h2', text: 'Vantagens Exclusivas de Cascais' },
      { type: 'ul', items: ['International schools: TASIS Portugal, Deutsche Schule, Cascais International School', 'Golfe: 4 campos top (Oitavos Dunes – World Top 100), marina com 650 lugares', 'Hospital particular e clínicas internacionais a 15 min', 'Comunidade anglófona consolidada — mais de 12.000 residentes britânicos e americanos', 'NHR/IFICI: residente em Cascais elegível para taxa flat 20% em rendimentos de trabalho qualificado'] },
      { type: 'h2', text: 'Mercado de Luxo: Quintinhas e Vilas' },
      { type: 'p', text: 'As propriedades premium de Cascais — vilas com piscina e jardim entre €1,5M e €6M — registaram liquidez recorde em 2025, com tempo médio de venda de 87 dias. Os compradores americanos representam 22% do segmento €2M+, seguidos de britânicos (17%) e franceses (13%).' },
      { type: 'highlight', label: 'Deal de Referência', text: 'Vila Quinta da Marinha (450m² hab., 2.800m² terreno, piscina aquecida, 5 suítes, adega): transaccionada a €4.200.000 em Outubro 2025 — €9.333/m². Tempo de mercado: 43 dias.' },
      { type: 'cta', text: 'Quer receber selecção exclusiva de imóveis em Cascais fora do mercado? A Agency Group tem acesso a off-market que não aparecem nos portais.' },
    ],
  },
  {
    slug: 'comprar-casa-algarve-guia',
    title: 'Algarve 2026: Guia Completo para Comprar Imóvel',
    description: 'Comprar casa no Algarve em 2026: Golden Triangle, Comporta, Vilamoura e os melhores investimentos na costa sul.',
    category: 'Guias de Compra',
    date: '2026-02-03',
    author: 'Agency Group',
    readingTime: 11,
    zona: 'Algarve',
    keywords: ['comprar casa algarve', 'imóveis algarve 2026', 'golden triangle algarve preços'],
    content: [
      { type: 'intro', text: 'O Algarve é o mercado turístico-residencial mais internacionalizado de Portugal, com 300 dias de sol, campos de golfe Michelin de topo e uma infra-estrutura hoteleira de classe mundial. Em 2026, o preço médio está em €3.941/m² — mas o Golden Triangle (Quinta do Lago, Vale do Lobo, Vilamoura) opera numa liga diferente.' },
      { type: 'h2', text: 'O Golden Triangle: Quinta do Lago, Vale do Lobo, Vilamoura' },
      { type: 'table', headers: ['Resort', 'Preço Casa €', 'Yield Turístico', 'Ocupação Média'], rows: [['Quinta do Lago (North/South)', '€2M–€15M', '5,5–7%', '78%'], ['Vale do Lobo (Royal/Ocean)', '€1,5M–€9M', '5–6,5%', '74%'], ['Vilamoura Marina', '€600K–€4M', '5–6%', '70%']] },
      { type: 'h2', text: 'Mercados Emergentes no Algarve 2026' },
      { type: 'ul', items: ['Alcântara do Marão / Tavira: zona nascente com preços 35–40% abaixo do Golden Triangle', 'Alvor / Portimão: reabilitação urbana, yields superiores a 6% em AL', 'Monchique Serra: turismo de wellness e natureza — procura crescente pós-pandemia', 'Sagres / Costa Vicentina: surf + natureza, procura nórdica e britânica consolidada'] },
      { type: 'h2', text: 'Licenciamento AL: O Que Mudou em 2026' },
      { type: 'p', text: 'O regime de Alojamento Local no Algarve manteve-se estável em 2026 após as alterações de 2023/2024. As licenças AL em zonas de contenção (NUTS III Algarve incluída) exigem aprovação municipal prévia. O Algarve mantém as suas zonas de contenção, mas a renovação de licenças existentes é automática.' },
      { type: 'highlight', label: 'Retorno Real — Exemplo', text: 'Villa Vale do Lobo €2.200.000, gestão turística full-service: receita bruta anual ~€154.000 (70% ocupação, €300 noite média). Custos gestão + manutenção ~€46.000. Cash flow líquido ~€108.000 = yield líquido 4,9%.' },
      { type: 'cta', text: 'Quer análise personalizada de investimento turístico no Algarve? A Agency Group elabora relatório completo com yields projectados, gestão e exit value em 10 anos.' },
    ],
  },
  {
    slug: 'comprar-casa-porto-guia',
    title: 'Porto 2026: Guia para Comprar Imóvel na Segunda Capital',
    description: 'Porto emerge como alternativa premium a Lisboa com yields superiores. Guia completo por bairros, preços e processo de compra.',
    category: 'Guias de Compra',
    date: '2026-02-10',
    author: 'Agency Group',
    readingTime: 10,
    zona: 'Porto',
    keywords: ['comprar casa porto', 'imóveis porto 2026', 'preço apartamento porto'],
    content: [
      { type: 'intro', text: 'O Porto é a grande surpresa do imobiliário português da última década. Com preço médio de €3.643/m² em 2026 — 27% abaixo de Lisboa — e yields de arrendamento 15–25% superiores, a cidade do Douro atrai crescente interesse de investidores europeus e americanos que procuram value com qualidade de vida.' },
      { type: 'h2', text: 'Bairros Prime e Preços 2026' },
      { type: 'table', headers: ['Bairro', 'Preço €/m²', 'Yield Bruto', 'Perfil'], rows: [['Foz do Douro', '€5.500–€9.000', '3,5–4,5%', 'HNWI, família'], ['Boavista / Serralves', '€4.200–€6.500', '4–5%', 'Executivo, expat'], ['Cedofeita / Miragaia', '€3.800–€5.800', '4,5–5,5%', 'Jovem profissional, turismo'], ['Ribeira / Bonfim', '€3.200–€5.200', '5–6,5%', 'Turismo curta duração'], ['Matosinhos', '€3.000–€4.500', '5–6%', 'Surf, lifestyle, tech']] },
      { type: 'h2', text: 'Porto vs Lisboa: Análise Comparativa' },
      { type: 'ul', items: ['Preço médio: Porto €3.643/m² vs Lisboa €5.000/m² (−27%)', 'Yield bruto médio: Porto 5,1% vs Lisboa 3,8% (+34%)', 'Crescimento 5 anos: Porto +94% vs Lisboa +78% (Porto supera)', 'Custos de vida 18% inferiores a Lisboa', 'Aeroporto Francisco Sá Carneiro: 43 destinos directos internacionais', 'Comunidade startup + NHR: ecossistema de expatriados em crescimento acelerado'] },
      { type: 'h2', text: 'Reabilitação Urbana: O Motor de Valorização' },
      { type: 'p', text: 'O Bonfim, Campanhã e Paranhos estão em plena transformação. Com mais de €850M em projectos de reabilitação aprovados para 2025–2028, bairros como Bonfim registaram +31% em 3 anos. Para investidores com horizonte 5 anos, estas zonas oferecem o melhor risco-retorno do Porto.' },
      { type: 'cta', text: 'Porto tem oportunidades off-market que não chegam aos portais. Contacte a Agency Group para selecção exclusiva.' },
    ],
  },
  {
    slug: 'comprar-casa-sintra-guia',
    title: 'Sintra: Viver num Palácio a 25 Minutos de Lisboa',
    description: 'O guia completo para comprar casa em Sintra em 2026 — das quintas históricas às vivendas modernas na Serra e na costa atlântica.',
    category: 'Guias de Compra',
    date: '2026-02-18',
    author: 'Agency Group',
    readingTime: 9,
    zona: 'Lisboa',
    keywords: ['comprar casa sintra', 'imóveis sintra 2026', 'quinta sintra comprar'],
    content: [
      { type: 'intro', text: 'Sintra é única em Portugal: Património UNESCO, microclima atlântico singular, palácios e quintas históricas a 30 minutos de Lisboa. Para compradores que recusam escolher entre cidade e natureza, Sintra oferece o melhor dos dois mundos a preços ainda razoáveis comparados com Cascais.' },
      { type: 'h2', text: 'Áreas Principais de Sintra' },
      { type: 'ul', items: ['Sintra Vila / Centro Histórico: casas de carácter, quinta renovada, turismo intenso', 'Colares / Várzea de Sintra: vinha centenária, tranquilidade, propriedades de charme', 'Galamares / Almoçageme: acesso à Praia Grande, surf, lifestyle', 'Almargem do Bispo / Mem Martins: acessibilidade A16, bom custo-benefício'], },
      { type: 'h2', text: 'Preços e Mercado 2026' },
      { type: 'p', text: 'Os preços em Sintra variam amplamente: um apartamento reabilitado no centro histórico atinge €4.500–€6.000/m²; uma quinta com 5.000m² de terreno pode custar €1,5M–€4M dependendo do estado de conservação e localização. Junto à costa (Praia Grande / Praia das Maçãs), o mercado de segunda habitação pressiona os preços para cima.' },
      { type: 'highlight', label: 'Atenção', text: 'Muitas propriedades em Sintra têm restrições urbanísticas de PGNU ou PNSAC (Parque Natural Sintra-Cascais). Verificar certidão de destaque e viabilidade de construção ANTES de qualquer sinal é obrigatório.' },
      { type: 'cta', text: 'A Agency Group tem access exclusivo a quintas históricas e propriedades off-market em Sintra. Fale connosco.' },
    ],
  },
  {
    slug: 'comprar-casa-comporta-guia',
    title: 'Comporta 2026: O Maldivas Europeu — Guia de Investimento',
    description: 'Comporta e Melides — o mercado mais exclusivo de Portugal em 2026. Preços, legislação, yields e o que esperar nos próximos 5 anos.',
    category: 'Guias de Compra',
    date: '2026-02-25',
    author: 'Agency Group',
    readingTime: 10,
    zona: 'Lisboa',
    keywords: ['comprar casa comporta', 'imóveis comporta 2026', 'melides propriedades'],
    content: [
      { type: 'intro', text: 'A Comporta tornou-se o endereço mais exclusivo de Portugal. Com areias brancas, piçarras e uma atmosfera "boho-luxury" que atrai celebrities e billionaires europeus, este triângulo de luxo (Comporta–Melides–Grândola) oferece escassez real num mercado em expansão controlada.' },
      { type: 'h2', text: 'Preços e Disponibilidade em 2026' },
      { type: 'table', headers: ['Zona', 'Tipo', 'Preço Range', 'Disponibilidade'], rows: [['Comporta Aldeia', 'Casa tradicional remodelada', '€800K–€2,5M', 'Escassa'], ['Brejos da Carregueira', 'Villa moderna piscina', '€1,5M–€5M', 'Limitada'], ['Melides / Carvalhal', 'Herdade / quinta', '€1,2M–€8M', 'Off-market maioritariamente'], ['Torre / Tróia', 'Apartamento resort', '€400K–€1,2M', 'Disponível']] },
      { type: 'h2', text: 'Regras Urbanísticas e Constrangimentos' },
      { type: 'p', text: 'A Comporta está inserida na ERPVA (Estrutura Regional de Protecção e Valorização Ambiental) e no PROT Alentejo Litoral. A construção nova é fortemente restringida — máximo 0,04 índice de edificabilidade em zonas RAN/REN. Isto garante a escassez que sustenta os preços a longo prazo.' },
      { type: 'h2', text: 'Yields e Retorno Turístico' },
      { type: 'ul', items: ['Alojamento local premium: €800–€2.500/noite em época alta (Julho–Agosto)', 'Ocupação anual: 55–65% para propriedades geridas profissionalmente', 'Yield bruto turístico: 4,5–6% sobre valor de aquisição', 'Valorização esperada 5 anos: +40–60% (Savills, Knight Frank estimates 2025)'] },
      { type: 'cta', text: 'Comporta tem muito mais off-market do que online. A Agency Group tem pipeline exclusivo de quintas e casas. Consulte-nos.' },
    ],
  },
  {
    slug: 'comprar-casa-madeira-guia',
    title: 'Madeira 2026: Guia Completo para Investir na Ilha Premium',
    description: 'Funchal e Madeira têm um dos mercados imobiliários mais dinâmicos de Portugal. Preços, CINM, NHR e o melhor clima da Europa.',
    category: 'Guias de Compra',
    date: '2026-03-04',
    author: 'Agency Group',
    readingTime: 9,
    zona: 'Madeira',
    keywords: ['comprar casa madeira', 'imóveis madeira funchal 2026', 'investir madeira portugal'],
    content: [
      { type: 'intro', text: 'A Madeira tem vindo a ultrapassar o continente em ritmo de valorização. Com preço médio de €3.760/m² em 2026, 22% de crescimento anual em 2024/2025, e os atractivos únicos do CINM (Centro Internacional de Negócios da Madeira) e clima atlântico perfeito, a ilha é uma das descobertas do imobiliário europeu.' },
      { type: 'h2', text: 'Funchal por Zonas' },
      { type: 'table', headers: ['Zona', 'Preço €/m²', 'Notas'], rows: [['Funchal Centro / Sé', '€3.500–€5.500', 'Reabilitação activa'], ['Lido / Estrada Monumental', '€4.200–€6.500', 'Prime residencial + resort'], ['Santo António / São Martinho', '€2.800–€4.200', 'Famílias locais e expat'], ['Caniçal / Machico', '€2.200–€3.200', 'Emergente, acesso aeroporto'], ['Ponta do Sol / Ribeira Brava', '€1.800–€2.800', 'Slow life, nómadas digitais']] },
      { type: 'h2', text: 'Vantagens Fiscais da Madeira' },
      { type: 'ul', items: ['CINM: taxa IRC de 5% para empresas qualificadas (vs 21% no continente)', 'NHR / IFICI aplicável: residentes elegíveis para isenção ou taxa reduzida', 'IMT: mesmas taxas que o continente, mas IMI municipal tendencialmente inferior', 'Ausência de herança local (ISA da Madeira) para estruturas correctas'] },
      { type: 'h2', text: 'Digital Nomads e Comunidade Internacional' },
      { type: 'p', text: 'A Madeira foi pioneira no movimento "remote work" europeu com o Ponta do Sol Digital Nomad Village. Em 2026, a ilha conta com mais de 8.000 residentes estrangeiros activos, uma comunidade anglófona crescente e eventos internacionais de networking mensais.' },
      { type: 'cta', text: 'Quer uma selecção das melhores propriedades em Funchal e na Madeira? A Agency Group tem presença activa na ilha.' },
    ],
  },
  {
    slug: 'comprar-casa-acores-guia',
    title: 'Açores 2026: O Mercado Mais Acessível de Portugal com Maior Potencial',
    description: 'Investir nos Açores em 2026 — São Miguel, Terceira, Faial: preços, incentivos regionais, turismo sustentável e potencial de valorização.',
    category: 'Guias de Compra',
    date: '2026-03-11',
    author: 'Agency Group',
    readingTime: 8,
    zona: 'Açores',
    keywords: ['comprar casa açores', 'imóveis são miguel açores', 'investir açores portugal'],
    content: [
      { type: 'intro', text: 'Com preço médio de €1.952/m² — menos de metade de Lisboa — e um turismo em explosão (+34% em 2024), os Açores representam a maior assimetria entre preço actual e potencial de mercado em Portugal. Para investidores early-mover, a oportunidade é única.' },
      { type: 'h2', text: 'As Ilhas por Potencial de Investimento' },
      { type: 'table', headers: ['Ilha', 'Preço Médio €/m²', 'Turismo', 'Potencial 5 anos'], rows: [['São Miguel (Ponta Delgada)', '€1.800–€2.800', 'Alto', '★★★★★'], ['Terceira (Angra do Heroísmo)', '€1.400–€2.200', 'Médio-Alto', '★★★★'], ['Faial (Horta)', '€1.200–€1.900', 'Médio', '★★★★'], ['Pico', '€900–€1.600', 'Crescente', '★★★★'], ['Flores / Corvo', '€600–€1.200', 'Nicho', '★★★']] },
      { type: 'h2', text: 'Incentivos Regionais' },
      { type: 'ul', items: ['SRRN (Subsistema Regional de Reabilitação): apoio até 40% para reabilitação de imóveis devolutos', 'IRS reduzido para residentes nos Açores: desconto automático de 20% sobre colecta IRS', 'IMI: taxas municipais entre 0,3%–0,5% — inferiores à média nacional', 'Licenças AL: menos restrições que Lisboa / Porto para alojamento turístico'] },
      { type: 'h2', text: 'Riscos a Considerar' },
      { type: 'p', text: 'Os Açores têm riscos sísmicos e vulcânicos que devem ser avaliados por engenheiro especializado. O seguro multiriscos é obrigatório para financiamento hipotecário e pode ter prémios superiores aos do continente. A liquidez do mercado é menor — tempos de venda de 6–18 meses são normais.' },
      { type: 'cta', text: 'Quer identificar as melhores oportunidades nos Açores antes da grande valorização? Contacte a Agency Group.' },
    ],
  },

  // ─────────────────────────────────────────────
  // INVESTIMENTO / FINANÇAS (8)
  // ─────────────────────────────────────────────
  {
    slug: 'rentabilidade-imoveis-portugal-2026',
    title: 'Rentabilidade de Imóveis em Portugal 2026: Análise Completa',
    description: 'Yields reais de imóveis em Portugal por zona e tipo em 2026. Análise comparativa com outros activos e como maximizar o retorno.',
    category: 'Investimento',
    date: '2026-01-08',
    author: 'Agency Group',
    readingTime: 11,
    keywords: ['rentabilidade imoveis portugal', 'yield imobiliario 2026', 'investimento imoveis retorno'],
    content: [
      { type: 'intro', text: 'O imobiliário português continua a oferecer uma das melhores relações risco-retorno da Europa Ocidental em 2026. Com yields de arrendamento entre 3,5% e 7% e valorização histórica anualizada de 8–12%, é uma classe de activo que combina rendimento corrente com apreciação de capital.' },
      { type: 'h2', text: 'Yields por Zona em 2026' },
      { type: 'table', headers: ['Zona', 'Yield Bruto', 'Yield Líquido Est.', 'Valorização 12m'], rows: [['Lisboa Centro', '3,5–4,5%', '2,8–3,5%', '+14%'], ['Lisboa Periférica', '4,5–5,5%', '3,5–4,3%', '+11%'], ['Porto Prime', '4,8–5,8%', '3,8–4,6%', '+16%'], ['Porto Emergente', '5,5–7%', '4,3–5,5%', '+22%'], ['Cascais', '3,8–5%', '2,9–4%', '+10%'], ['Algarve (turístico)', '5–7%', '3,5–5%', '+12%'], ['Madeira', '5–6,5%', '3,8–5,2%', '+22%']] },
      { type: 'h2', text: 'Yield Bruto vs Yield Líquido: O Que Importa' },
      { type: 'ul', items: ['Yield bruto = renda anual / preço compra × 100', 'Yield líquido = (renda − IMI − condomínio − seguros − manutenção − IMT amortizado) / preço compra × 100', 'Desconto médio bruto→líquido: 20–35% dependendo do tipo de imóvel', 'Para AL (Airbnb): adicionar custo de gestão operacional (18–25% das receitas)'] },
      { type: 'h2', text: 'TIR a 10 Anos: Holding Period Analysis' },
      { type: 'p', text: 'Considerando yield líquido de 4% + valorização anual de 9% + alavancagem com LTV 70% a taxa 3,2%, a TIR do equity num imóvel prime em Porto pode superar 18% a 10 anos. O efeito de alavancagem multiplica o retorno sobre o capital próprio de forma significativa.' },
      { type: 'highlight', label: 'Análise Financeira', text: 'Apartamento Porto €350.000 — LTV 70% (€245.000 financiado). Capital próprio: €105.000. Renda líquida: €1.400/mês. Cash flow após prestação (~€1.100): €300/mês. Valorização 10 anos a 9%: €828.000. TIR equity: ~21,4%.' },
      { type: 'h2', text: 'Imobiliário vs Outros Activos em 2026' },
      { type: 'table', headers: ['Activo', 'Retorno Esperado', 'Risco', 'Liquidez'], rows: [['Imobiliário Portugal', '11–16% (TIR)', 'Médio', 'Baixa'], ['S&P 500 (histórico)', '10–12%', 'Alto', 'Alta'], ['Obrigações PT 10Y', '3,1%', 'Baixo', 'Média'], ['Ouro', '6–8%', 'Médio', 'Alta'], ['Conta Poupança', '2,3%', 'Mínimo', 'Imediata']] },
      { type: 'cta', text: 'Quer análise de TIR personalizada para o imóvel que está a considerar? A Agency Group elabora modelo financeiro completo incluindo cenários de saída.' },
    ],
  },
  {
    slug: 'financiamento-hipotecario-portugal-estrangeiros',
    title: 'Financiamento Hipotecário em Portugal para Estrangeiros 2026',
    description: 'Como obter hipoteca em Portugal sendo estrangeiro: bancos, requisitos, LTV, spreads e documentação necessária em 2026.',
    category: 'Investimento',
    date: '2026-01-29',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['hipoteca portugal estrangeiros', 'financiamento imóvel portugal não residente', 'empréstimo habitação portugal 2026'],
    content: [
      { type: 'intro', text: 'Obtere financiamento hipotecário em Portugal como estrangeiro é mais simples do que a maioria antecipa — desde que o processo seja bem gerido. Os principais bancos portugueses financiam não-residentes, com condições competitivas para perfis prime.' },
      { type: 'h2', text: 'Condições Típicas para Não-Residentes em 2026' },
      { type: 'table', headers: ['Banco', 'LTV Máx (NR)', 'Spread Médio', 'Prazo Máx', 'Notas'], rows: [['CGD', '70%', '0,95%', '40 anos', 'Exige conta em Portugal'], ['Millennium BCP', '70%', '0,9%', '40 anos', 'Abertura online disponível'], ['Novo Banco', '70%', '0,85%', '35 anos', 'Bom para HNWI'], ['Santander Totta', '65%', '1,1%', '40 anos', 'Processos ágeis'], ['BPI', '70%', '0,95%', '40 anos', 'BNP Paribas partnership']] },
      { type: 'h2', text: 'Documentação Necessária (NHR / Não Residente)' },
      { type: 'ul', items: ['Passaporte válido + NIF português (obtenção online em 24h via portal AT)', 'IRS / tax returns dos últimos 2 anos no país de residência (apostilados)', 'Extractos bancários últimos 6 meses', 'Prova de rendimentos: contrato de trabalho ou extracto de rendimentos empresa', 'Avaliação do imóvel por perito aprovado pelo banco', 'Seguro de vida (obrigatório para hipoteca) e seguro multi-riscos habitação'] },
      { type: 'h2', text: 'Euribor e Taxa Efectiva em 2026' },
      { type: 'p', text: 'A Euribor a 12 meses estabilizou nos 2,1% em Março 2026, com expectativas de BCE de dois cortes adicionais até final do ano. Com spread de 0,9%, a TAN efectiva para não-residentes prime situa-se entre 2,8%–3,2%. Isto traduz-se em prestação de ~€940/mês para €200.000 a 30 anos.' },
      { type: 'highlight', label: 'Dica Importante', text: 'Abrir conta bancária em Portugal ANTES de iniciar o processo hipotecário reduz o prazo de aprovação em 3–4 semanas. CGD e BCP têm processo de abertura online para não-residentes disponível em 48h.' },
      { type: 'cta', text: 'A Agency Group trabalha com mortgage brokers especializados em clientes internacionais. Obtenha aprovação prévia em 5 dias úteis.' },
    ],
  },
  {
    slug: 'investimento-arrendamento-portugal-guia',
    title: 'Investir para Arrendar em Portugal: O Guia Definitivo 2026',
    description: 'Estratégia de buy-to-let em Portugal: escolha do imóvel, gestão, lei do arrendamento, yields e optimização fiscal para landlords.',
    category: 'Investimento',
    date: '2026-02-05',
    author: 'Agency Group',
    readingTime: 12,
    keywords: ['investimento arrendamento portugal', 'buy to let portugal', 'rendimento arrendamento imóvel'],
    content: [
      { type: 'intro', text: 'O mercado de arrendamento em Portugal registou uma escassez histórica de oferta em 2025/2026, com procura 340% superior à oferta disponível em Lisboa e 280% no Porto. Para landlords bem posicionados, este desequilíbrio estrutural significa yields crescentes e ocupação praticamente garantida.' },
      { type: 'h2', text: 'Tipos de Arrendamento: Longa Duração vs AL' },
      { type: 'table', headers: ['Modalidade', 'Yield Bruto', 'Gestão', 'Risco', 'Fiscalidade'], rows: [['Arrendamento longa duração', '3,5–5%', 'Baixa', 'Baixo', 'IRS 25% taxa especial'], ['AL (Airbnb) gestão própria', '6–9%', 'Alta', 'Médio', 'Cat. B, escalão marginal'], ['AL com gestora profissional', '4,5–6,5%', 'Mínima', 'Médio', 'Cat. B ou empresa']] },
      { type: 'h2', text: 'Lei do Arrendamento 2026: O Que Mudou' },
      { type: 'ul', items: ['Prazo mínimo de contrato: 1 ano (mantido)', 'Actualização anual de renda: limitada a 2% ou IPC (o que for maior)', 'Denúncia pelo senhorio: 120 dias de aviso prévio para não renovação', 'Despejo por incumprimento: prazo médio caiu para 4–6 meses em 2025', 'Programa Arrendamento Acessível: isenção fiscal total para rendas abaixo do tecto definido (15–20% abaixo do mercado)'] },
      { type: 'h2', text: 'Fiscalidade do Arrendamento' },
      { type: 'p', text: 'Rendimentos de arrendamento são tributados à taxa especial de 25% em IRS (opção de englobamento se favorável). Despesas dedutíveis: IMI, condomínio, seguros, obras de conservação, amortização do empréstimo (juros), honorários de gestão. Senhores com casa com certificado energético B ou superior beneficiam de taxa reduzida de 5% durante 5 anos (DL 67/2023).' },
      { type: 'cta', text: 'Quer um portfolio de imóveis para arrendamento com análise de rentabilidade completa? A Agency Group constrói estratégias buy-to-let personalizadas.' },
    ],
  },
  {
    slug: 'portfolio-diversificacao-imobiliaria-portugal',
    title: 'Diversificação Imobiliária em Portugal: Como Construir um Portfolio Eficiente',
    description: 'Estratégias de diversificação para investidores imobiliários em Portugal: tipos de activo, zonas, tickets e gestão de risco.',
    category: 'Investimento',
    date: '2026-02-12',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['portfolio imobiliário portugal', 'diversificação investimento imóveis', 'imobiliário portugal family office'],
    content: [
      { type: 'intro', text: 'Os investidores mais sofisticados tratam o imobiliário como uma classe de activo com portfolio próprio — diversificando por zona, tipo, horizonte temporal e estratégia de exit. Em Portugal, a diversidade geográfica e de segmentos permite construir portfolios altamente eficientes com risco controlado.' },
      { type: 'h2', text: 'Matriz de Diversificação: Core / Value-Add / Opportunistic' },
      { type: 'table', headers: ['Estratégia', 'Activo', 'Zona', 'Retorno Alvo', '% Portfolio'], rows: [['Core (renda segura)', 'Apartamento residencial', 'Lisboa/Cascais', '4–5% yield', '40–50%'], ['Core Plus', 'Imóvel comercial prime', 'Lisboa CBD', '5–6% yield', '15–20%'], ['Value-Add', 'Reabilitação urbana', 'Porto/Bonfim', '15–25% TIR', '20–30%'], ['Opportunistic', 'Terreno / off-plan', 'Açores/Alentejo', '30%+ TIR', '10–15%']] },
      { type: 'h2', text: 'Dimensão Mínima por Estratégia' },
      { type: 'ul', items: ['Core residencial: tickets a partir de €200K (apartamento Porto) ou €400K (Lisboa)', 'Value-add urbano: mínimo €300–500K para projecto de reabilitação viável', 'Turístico / AL premium: €600K–€1,5M para operação profissional no Algarve', 'Family office (€2M+): acesso a deals off-market, quintas históricas, projectos de promoção'] },
      { type: 'h2', text: 'Gestão Profissional vs DIY' },
      { type: 'p', text: 'Para portfolios acima de 3 imóveis, a gestão profissional (property manager) gera retornos líquidos superiores ao DIY. Os custos de gestão (8–12% das rendas) são amplamente compensados pela minimização de vacância, manutenção proactiva e gestão de inquilinos. Para investidores não-residentes, é simplesmente indispensável.' },
      { type: 'cta', text: 'A Agency Group gere portfolios imobiliários para clientes internacionais em Portugal. Da aquisição à gestão corrente.' },
    ],
  },
  {
    slug: 'mais-valias-imoveis-portugal-guia-fiscal',
    title: 'Mais-Valias Imobiliárias em Portugal 2026: Guia Fiscal Completo',
    description: 'Tributação das mais-valias na venda de imóveis em Portugal em 2026: residentes, não-residentes, exclusões e optimização legal.',
    category: 'Investimento',
    date: '2026-02-19',
    author: 'Agency Group',
    readingTime: 9,
    keywords: ['mais valias imóveis portugal', 'imposto venda imóvel portugal', 'tributação imobiliária portugal 2026'],
    content: [
      { type: 'intro', text: 'As mais-valias na venda de imóveis em Portugal são tributadas de forma diferenciada consoante se é residente ou não-residente, pessoa singular ou colectiva, e a natureza do imóvel. Conhecer as regras é essencial para optimizar a saída de qualquer investimento.' },
      { type: 'h2', text: 'Regra Geral: Residentes em Portugal' },
      { type: 'p', text: 'Para residentes fiscais, as mais-valias imobiliárias entram em IRS e são tributadas sobre 50% do valor (a outra metade é excluída). À taxa marginal do escalão, o custo efectivo varia entre 11,2% (escalão mínimo) e 24% (escalão máximo). Opção de englobamento só faz sentido para escalões baixos.' },
      { type: 'h2', text: 'Exclusões e Benefícios Fiscais' },
      { type: 'ul', items: ['Habitação própria e permanente + reinvestimento total em nova HPP: exclusão total de mais-valia', 'Reinvestimento parcial em nova HPP: exclusão proporcional', 'Imóveis adquiridos antes de 1989: excluídos de tributação', 'NHR / IFICI: mais-valias de imóveis em Portugal são tributadas normalmente (sem benefício NHR)'] },
      { type: 'h2', text: 'Não-Residentes: Tributação em 2026' },
      { type: 'p', text: 'Não-residentes de países com ADT com Portugal: 28% sobre a totalidade da mais-valia (sem excluir 50%). Não-residentes de países sem ADT: mesma regra. Desde a decisão Hollmann do TJUE (2015), Portugal deve tratar cidadãos da UE/EEE igualmente, oferecendo a opção de regime de residente.' },
      { type: 'h2', text: 'Empresas: SGPS e Holding Imobiliária' },
      { type: 'p', text: 'Através de uma holding portuguesa (SA ou Lda), as mais-valias imobiliárias qualificam para participation exemption se a holding detiver pelo menos 10% do capital da empresa que detém o imóvel por mais de 12 meses. Estrutura ideal para portfolios acima de €2M.' },
      { type: 'highlight', label: 'Atenção Legal', text: 'Esta informação é de carácter geral e não substitui consultadoria fiscal personalizada. Consulte sempre um contabilista certificado ou advogado fiscal antes de tomar decisões de investimento.' },
      { type: 'cta', text: 'A Agency Group trabalha com fiscalistas especializados em imobiliário para optimizar a saída dos seus investimentos.' },
    ],
  },
  {
    slug: 'promocao-imobiliaria-portugal-como-investir',
    title: 'Promoção Imobiliária em Portugal: Como Investir em Desenvolvimento 2026',
    description: 'Guia completo para investir em promoção imobiliária em Portugal: análise de viabilidade, licenciamento, financiamento e margens.',
    category: 'Investimento',
    date: '2026-02-26',
    author: 'Agency Group',
    readingTime: 11,
    keywords: ['promoção imobiliária portugal', 'desenvolvimento imobiliário investimento', 'reabilitação urbana portugal investir'],
    content: [
      { type: 'intro', text: 'A promoção imobiliária oferece os maiores retornos do sector — mas também os maiores riscos. Em Portugal, a escassez de oferta nova em Lisboa e Porto cria margens de promoção de 25–45%, tornando o desenvolvimento imobiliário altamente atraente para investidores capitalizados.' },
      { type: 'h2', text: 'Tipos de Projecto de Promoção' },
      { type: 'ul', items: ['Reabilitação urbana: edifício devoluto → apartamentos premium. Custo total €1.500–€2.500/m². Margem: 30–50%', 'Loteamento e construção nova: terreno + construção nova. Custo total €2.000–€3.200/m². Margem: 25–40%', 'Off-plan: compra de terreno, licença, pré-vendas antes de construir. Risco alto, retorno 40%+', 'Retrofit energético: upgrade de edifícios com certificados energéticos baixos. Incentivos IFRRU disponíveis'] },
      { type: 'h2', text: 'Análise de Viabilidade: Números-Chave' },
      { type: 'table', headers: ['Item', 'Custo Estimado', 'Observações'], rows: [['Aquisição terreno/edifício', '35–45% do GDV', 'Variável por zona'], ['Construção / reabilitação', '€1.500–€2.500/m²', '+ 15% contingência'], ['Licenciamento e projectos', '2–4% do custo obra', 'Variável por câmara'], ['Financiamento bancário', '5–8% a.a. (mezzanine)', 'LTV 65% máx. bancário'], ['Comercialização + IVA', '5–8% das vendas', 'AMI + marketing']] },
      { type: 'h2', text: 'Prazo de Licenciamento: A Grande Variável' },
      { type: 'p', text: 'O licenciamento é o maior risco temporal na promoção portuguesa. Lisboa: 18–36 meses para operações de reabilitação significativa. Porto: 12–24 meses. Cascais: 12–18 meses. A nova lei de licenciamento simplificado (DL 10/2024) reduziu parcialmente os prazos mas os atrasos administrativos continuam.' },
      { type: 'cta', text: 'A Agency Group identifica terrenos e edifícios com potencial de promoção em Lisboa, Porto e Algarve. Consultoria de viabilidade disponível.' },
    ],
  },
  {
    slug: 'imoveis-comerciais-portugal-investimento',
    title: 'Imóveis Comerciais em Portugal 2026: Escritórios, Retalho e Logística',
    description: 'Mercado de imóveis comerciais em Portugal em 2026: yields, tendências, prime CBD e como aceder a activos institucionais.',
    category: 'Investimento',
    date: '2026-03-05',
    author: 'Agency Group',
    readingTime: 9,
    keywords: ['imóveis comerciais portugal', 'escritórios lisboa investimento', 'logística imobiliário portugal'],
    content: [
      { type: 'intro', text: 'O mercado de imóveis comerciais em Portugal diversificou significativamente em 2025/2026. Escritórios prime em Lisboa CBD, warehouses logísticos junto a Setúbal, e retalho de bairro em recuperação após o pós-Covid oferecem alternativas atraentes ao residencial.' },
      { type: 'h2', text: 'Yields por Segmento em 2026' },
      { type: 'table', headers: ['Segmento', 'Yield Prime', 'Yield Secundário', 'Tendência'], rows: [['Escritórios Lisboa CBD', '4,25%', '5,5%', '→ Estável'], ['Retalho rua prime (Lisboa)', '4,75%', '6%', '↑ Recuperação'], ['Logística (Grande Lisboa)', '4,5%', '5,75%', '↑ Alta procura'], ['Hoteleiro Lisboa', '5,5%', '7%', '↑ Fortíssimo'], ['Industrial light', '5,25%', '6,5%', '→ Estável']] },
      { type: 'h2', text: 'Tendências 2026: O Que Está a Acontecer' },
      { type: 'ul', items: ['Escritórios: flex/coworking representa 28% da absorção total. Escritórios ESG premium têm ocupação total', 'Logística: e-commerce e nearshoring criam procura recorde. Porto e Azambuja são hotspots', 'Hoteleiro: Lisboa no top 5 europeu de RevPAR growth. Transacções hoteleiras bateram €850M em 2025', 'Retalho: high street recuperou. Parque das Nações e Belém são os novos prime retail'] },
      { type: 'cta', text: 'A Agency Group tem deal flow de activos comerciais em Portugal para investidores institucionais e family offices.' },
    ],
  },
  {
    slug: 'avm-avaliacao-imobiliaria-como-funciona',
    title: 'AVM: Como Funciona a Avaliação Automática de Imóveis em Portugal',
    description: 'O que é um AVM (Automated Valuation Model) e como usar esta tecnologia para avaliar imóveis em Portugal com precisão.',
    category: 'Investimento',
    date: '2026-03-12',
    author: 'Agency Group',
    readingTime: 7,
    keywords: ['AVM imóveis portugal', 'avaliação automática imóvel', 'quanto vale minha casa portugal'],
    content: [
      { type: 'intro', text: 'Os AVMs (Automated Valuation Models) revolucionaram a forma como avaliamos imóveis. Usando machine learning sobre milhares de transacções reais, um bom AVM consegue estimar o valor de mercado com margem de erro inferior a 8% em 75% dos casos — em segundos, sem visita.' },
      { type: 'h2', text: 'Como Funciona o AVM da Agency Group' },
      { type: 'ul', items: ['47 variáveis de entrada: localização (GPS), área, tipologia, andar, orientação, estado', 'Algoritmo de comparáveis: cruza com transacções reais nos últimos 18 meses num raio de 500m', 'Ajustamento hedónico: pondera diferenças de andar, luz, vista, estado de conservação', 'Contexto de mercado: integra tendências de preço zonais e índice de procura actual', 'Output: valor de mercado + intervalo de confiança 80% + comparáveis utilizados'] },
      { type: 'h2', text: 'Limitações do AVM vs Avaliação Presencial' },
      { type: 'p', text: 'O AVM é excelente para triagem rápida e negociação informada. Para financiamento bancário, é necessária avaliação presencial por perito aprovado pelo Banco de Portugal (CMVM). O AVM não avalia obras necessárias, singularidades arquitectónicas ou factores emocionais de valor.' },
      { type: 'h2', text: 'Quando Usar um AVM' },
      { type: 'ul', items: ['Antes de fazer proposta: saber se o preço pedido é justo', 'Antes de pôr à venda: calibrar o preço de listagem', 'Due diligence rápida em portais: filtrar oportunidades abaixo de mercado', 'Revisão anual do portfolio: monitorizar valorização dos activos detidos'] },
      { type: 'cta', text: 'Use o AVM gratuito da Agency Group — resultado em 60 segundos para qualquer imóvel em Portugal.' },
    ],
  },

  // ─────────────────────────────────────────────
  // COMPRADORES INTERNACIONAIS (6)
  // ─────────────────────────────────────────────
  {
    slug: 'americanos-comprar-portugal-guia',
    title: 'Americans Buying Property in Portugal: Complete 2026 Guide',
    description: 'How Americans can buy real estate in Portugal in 2026: process, financing, taxes, NHR visa and the best areas for US buyers.',
    category: 'Compradores Internacionais',
    date: '2026-01-12',
    author: 'Agency Group',
    readingTime: 11,
    keywords: ['americans buying property portugal', 'us citizens real estate portugal', 'portugal property guide american buyers'],
    content: [
      { type: 'intro', text: 'Americans represent 16% of all international buyers in the €500K–€3M segment in Portugal — and the number is growing. Dollar-denominated wealth, dissatisfaction with US urban costs, and Portugal\'s world-class quality of life are driving a generational shift. Here\'s everything US buyers need to know.' },
      { type: 'h2', text: 'Why Americans Choose Portugal' },
      { type: 'ul', items: ['Safety: Portugal is the 7th safest country in the world (GPI 2025)', 'Healthcare: Universal system + private hospitals with English-speaking staff', 'Cost of living: 40-55% below major US metros (NYC, SF, LA)', 'English proficiency: 62% of Portuguese speak English (highest in Southern Europe)', 'Property prices: €500K buys a 3-bed apartment in Lisbon prime — equivalent would cost €3M+ in Manhattan', 'NHR/IFICI: potential 20% flat tax on Portuguese-source employment income for 10 years'] },
      { type: 'h2', text: 'The Buying Process for Americans' },
      { type: 'ul', items: ['NIF (tax number): obtainable online in 24h — required for everything', 'Bank account: CGD, BCP and Santander have English-speaking expat desks', 'No restrictions: Americans have full right to purchase any property in Portugal', 'Mortgage: Portuguese banks finance up to 70% LTV for non-residents. DSCR typically requires proof of 2x monthly installment in income', 'Wire transfer: Portugal accepts USD wire — bank converts at spot. Plan 3 business days for clearing'] },
      { type: 'h2', text: 'FATCA & US Tax Considerations' },
      { type: 'p', text: 'US citizens are taxed on worldwide income regardless of residence. Portugal-US tax treaty avoids double taxation on most income streams. Portuguese rental income is reportable on US taxes (Form 1116 for foreign tax credits). Capital gains from Portuguese property sale are reportable in the US but foreign tax credits apply. FBAR filing required if Portuguese bank account exceeds $10,000.' },
      { type: 'h2', text: 'Best Areas for American Buyers in 2026' },
      { type: 'table', headers: ['Area', 'Budget', 'Why Americans Love It'], rows: [['Cascais', '€600K–€3M', 'English schools, beach, 30min Lisbon'], ['Lisbon (Príncipe Real)', '€800K–€3M', 'Walkable, cosmopolitan, great restaurants'], ['Algarve (Quinta do Lago)', '€1.5M–€6M', 'Golf, beach, resort amenities'], ['Porto (Foz)', '€500K–€2M', 'Lower cost, great food/wine culture'], ['Comporta', '€1M–€5M', 'Slow luxury, Hamptons vibe']] },
      { type: 'cta', text: 'Agency Group has English-speaking agents experienced with US buyers. We handle everything from NIF to keys. Get in touch.' },
    ],
  },
  {
    slug: 'franceses-comprar-portugal-guia',
    title: 'Français qui Achètent au Portugal: Guide Complet 2026',
    description: 'Guide complet pour les acheteurs français souhaitant investir dans l\'immobilier au Portugal en 2026: fiscalité, visa, meilleurs quartiers.',
    category: 'Compradores Internacionais',
    date: '2026-01-19',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['français acheter portugal', 'immobilier portugal français 2026', 'investir portugal acheteur français'],
    content: [
      { type: 'intro', text: 'Les Français représentent 13% des acheteurs internationaux au Portugal — le deuxième groupe le plus important. La proximité culturelle, la langue latine, la qualité de vie et un régime fiscal attractif (NHR/IFICI) en font la destination numéro un pour les Français cherchant à s\'installer ou à investir à l\'étranger.' },
      { type: 'h2', text: 'Pourquoi le Portugal Attire les Français' },
      { type: 'ul', items: ['Fiscalité: NHR/IFICI — taux fixe de 20% sur revenus professionnels portugais pendant 10 ans', 'Pensions françaises au Portugal: conventionnellement exonérées en France, imposées au Portugal à des taux souvent inférieurs', 'Proximité: vol direct Paris-Lisbonne 2h15. Air France, TAP, EasyJet depuis CDG, ORY, BVA', 'Communauté: plus de 80.000 Français résidents en Portugal en 2026', 'Immobilier: au moins 40% moins cher qu\'à Paris pour qualité équivalente'] },
      { type: 'h2', text: 'Fiscalité Franco-Portugaise: Points Clés' },
      { type: 'p', text: 'La convention fiscale France-Portugal du 14 janvier 1971 régit la double imposition. Les revenus immobiliers de source portugaise sont imposés au Portugal. Les plus-values immobilières sont imposées au Portugal. Les pensions privées françaises sont en général imposables au Portugal à 10% (régime NHR historique) ou selon le barème ordinaire.' },
      { type: 'h2', text: 'Quartiers Préférés des Acheteurs Français' },
      { type: 'table', headers: ['Quartier / Zone', 'Budget', 'Profil'], rows: [['Cascais / Estoril', '€500K–€3M', 'Famille, cadre supérieur'], ['Príncipe Real / Chiado', '€700K–€2,5M', 'Urbain, culturel'], ['Alfama / Graça', '€400K–€1,5M', 'Bobo, artistique'], ['Algarve Portimão', '€300K–€1M', 'Retraite, soleil'], ['Porto Boavista', '€350K–€1,2M', 'Investissement locatif']] },
      { type: 'cta', text: 'Agency Group dispose d\'agents francophones spécialisés dans l\'accompagnement des acheteurs français au Portugal. Contactez-nous.' },
    ],
  },
  {
    slug: 'britanicos-comprar-portugal-post-brexit',
    title: 'British Buyers in Portugal Post-Brexit: The Complete 2026 Guide',
    description: 'How British citizens can still buy property and live in Portugal after Brexit. Visas, residency, process and best areas for UK buyers.',
    category: 'Compradores Internacionais',
    date: '2026-01-26',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['british buying property portugal', 'uk citizens portugal post brexit', 'english buyers portugal 2026'],
    content: [
      { type: 'intro', text: 'Brexit changed the residency rules but not the passion. British buyers remain the 3rd largest international group in Portugal (9% of the €500K–€3M segment), and the fundamentals haven\'t changed: incredible weather, English widely spoken, Anglophone schools, and prices that make UK property look eye-watering.' },
      { type: 'h2', text: 'Post-Brexit: What Changed for British Buyers' },
      { type: 'ul', items: ['No right to free movement: UK citizens need a visa/residency permit for stays over 90 days in any 180-day period', 'D7 Passive Income Visa: easiest route. Requires proving €760/month passive income (pension, rent, dividends)', 'D8 Digital Nomad Visa: for remote workers earning min. €3,040/month', 'Golden Visa: €500K+ property investment still qualifies (but residential properties limited to interior/islands)', 'No property purchase restrictions: British nationals can buy freely in Portugal'] },
      { type: 'h2', text: 'The 90/180 Day Rule: Practical Implications' },
      { type: 'p', text: 'Without a residency permit, British citizens can stay max 90 days in any 180-day period in the Schengen Area. If you plan to use a Portuguese property for longer periods, getting the D7 or another residency visa is strongly recommended. Many British owners get residency to enjoy Portugal freely.' },
      { type: 'h2', text: 'Popular Areas for British Buyers' },
      { type: 'ul', items: ['Cascais: largest English-speaking community in Portugal. TASIS Portugal, St Julian\'s School', 'Algarve: British expat communities in Vilamoura, Tavira, Lagos — British pubs, football on TV', 'Lisbon (Lapa / Belém): historic areas, city life, English-speaking services', 'Silver Coast (Óbidos, Peniche): dramatic Atlantic coast, growing British community, affordable prices'] },
      { type: 'cta', text: 'Agency Group\'s English-speaking team guides British buyers from visa advice to handover of keys. Contact us for a free consultation.' },
    ],
  },
  {
    slug: 'compradores-brasileiros-imoveis-portugal',
    title: 'Brasileiros a Comprar Imóveis em Portugal: O Guia Completo 2026',
    description: 'Tudo que o comprador brasileiro precisa saber para comprar imóvel em Portugal em 2026: processo, impostos, vistos e melhores bairros.',
    category: 'Compradores Internacionais',
    date: '2026-02-02',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['brasileiros comprar imóveis portugal', 'imóveis portugal para brasileiros 2026', 'comprar casa portugal brasil'],
    content: [
      { type: 'intro', text: 'Os brasileiros são o grupo de compradores estrangeiros mais numeroso no segmento €100K–€500K e crescem rapidamente no €500K+. A língua comum, a facilidade de adaptação, os laços históricos e o Acordo de Igualdade de Direitos entre Brasil e Portugal tornam a transição particularmente suave.' },
      { type: 'h2', text: 'Vantagens Exclusivas para Brasileiros' },
      { type: 'ul', items: ['Acordo de Igualdade: brasileiros com residência em Portugal têm direitos equivalentes aos cidadãos portugueses em muitas áreas', 'Visto D3: para trabalhadores qualificados — médicos, engenheiros, TI. Aprovação rápida', 'Visto D8 (Nómada Digital): para trabalhadores remotos e freelancers com renda mínima de €3.040/mês', 'Língua: sem barreira linguística — integração muito mais fácil que para outras nacionalidades', 'Comunidade: ~300.000 brasileiros em Portugal (maior comunidade estrangeira)'] },
      { type: 'h2', text: 'Processo de Compra para Brasileiros' },
      { type: 'p', text: 'Brasileiros residentes em Portugal compram exactamente como nacionais. Não-residentes precisam de NIF (obtenção online ou via consulado) e conta bancária portuguesa. O financiamento hipotecário para não-residentes é possível com LTV até 70%, mas requer prova de rendimentos documentada.' },
      { type: 'h2', text: 'Bairros Favoritos em Lisboa e Porto' },
      { type: 'ul', items: ['Lisboa: Mouraria, Martim Moniz, Intendente — bairros com forte presença brasileira e boa ligação', 'Lisboa premium: Alfama, Graça, Bairro Alto — lifestyle e turismo', 'Porto: Bonfim e Campanhã — reabilitação activa, preços acessíveis', 'Almada / Setúbal: alternativa mais económica a Lisboa, boa acessibilidade'] },
      { type: 'cta', text: 'A Agency Group tem equipa com experiência em compradores brasileiros. Do NIF às chaves, tratamos de tudo.' },
    ],
  },
  {
    slug: 'compradores-medio-oriente-portugal',
    title: 'Middle East Buyers in Portugal: Investment Guide 2026',
    description: 'Why buyers from UAE, Saudi Arabia and Qatar are choosing Portugal. Visa options, best properties and investment strategies for MENA buyers.',
    category: 'Compradores Internacionais',
    date: '2026-02-09',
    author: 'Agency Group',
    readingTime: 9,
    keywords: ['middle east buyers portugal', 'uae investors portugal property', 'arabic property investment portugal'],
    content: [
      { type: 'intro', text: 'Buyers from the Middle East (UAE, Saudi Arabia, Qatar, Kuwait, Lebanon) represent the fastest-growing segment at the €1M–€5M+ price point in Portugal. With an average ticket of €3.2M and strong preference for prime properties with privacy, this demographic is reshaping the ultra-luxury market.' },
      { type: 'h2', text: 'Why Portugal for MENA Buyers' },
      { type: 'ul', items: ['Halal food: Lisbon has 40+ certified halal restaurants and growing Muslim community', 'Proximity: 4h direct flight from Dubai/Riyadh to Lisbon', 'Privacy & security: Portugal ranks 7th globally in safety (GPI 2025)', 'Education: excellent international schools with IB curriculum', 'Golden Visa (D8 / ARI): structured investment route to EU residency', 'No capital gains on foreign-source income for new residents', 'Property pricing: comparable Riviera/Monaco properties cost 3–5x more'] },
      { type: 'h2', text: 'Preferred Property Types' },
      { type: 'ul', items: ['Fully-walled estates with private gardens and pools: Cascais, Sintra, Comporta', 'Penthouse with river/ocean views: Lisboa (Chiado, Príncipe Real, Avenida da Liberdade)', 'Herdades with equestrian facilities: Alentejo, Ribatejo', 'Resort residences with managed services: Algarve (Quinta do Lago, Vale do Lobo)'] },
      { type: 'h2', text: 'Investment Structures' },
      { type: 'p', text: 'MENA buyers typically structure acquisitions through Portuguese or Luxembourg SPVs for privacy and succession planning. The Golden Visa via capital transfer (€500K+ in qualifying funds or €250K+ in cultural heritage) is a popular route for UAE and Saudi nationals seeking EU mobility.' },
      { type: 'cta', text: 'Agency Group provides Arabic-speaking support and has an exclusive portfolio of properties matching MENA buyer preferences. Contact us in English or Arabic.' },
    ],
  },
  {
    slug: 'compradores-chines-asiatico-portugal-guia',
    title: 'Chinese & Asian Buyers in Portugal: Complete Investment Guide 2026',
    description: 'How Chinese, Hong Kong and Asian buyers can invest in Portuguese property in 2026: golden visa, process, best properties and legal tips.',
    category: 'Compradores Internacionais',
    date: '2026-02-16',
    author: 'Agency Group',
    readingTime: 9,
    keywords: ['chinese buyers portugal property', 'golden visa portugal chinese', 'asian investors portugal real estate'],
    content: [
      { type: 'intro', text: 'Chinese and broader Asian buyers (mainland China, Hong Kong, Taiwan, Singapore) represent 8% of international buyers in Portugal\'s €500K–€3M segment. Historically driven by the Golden Visa program, this community has evolved toward lifestyle purchase and long-term residency planning.' },
      { type: 'h2', text: 'Current Golden Visa Options for Chinese Buyers' },
      { type: 'ul', items: ['ARI (Autorização de Residência para Investimento) – Golden Visa 2026:', '€500,000 investment in qualifying Portuguese investment funds (most common route)', '€250,000 in cultural heritage or artistic production', 'Direct residential property: no longer qualifies for coastal/metropolitan areas since 2024', 'Interior regions and islands: direct property investment still qualifies (€500K)'] },
      { type: 'h2', text: 'Process & Timeline for Chinese Buyers' },
      { type: 'ul', items: ['Obtain NIF: can be done remotely via representative or in person at Portuguese consulate', 'Open Portuguese bank account: CGD has Mandarin-speaking staff at Lisbon HQ', 'Make qualifying investment: wire transfer minimum €500K', 'Apply for ARI via SEF/AIMA: currently 8–14 months wait for first approval', 'Residency card: 2-year initial, then renewable. 5 years → Portuguese citizenship eligibility'] },
      { type: 'h2', text: 'WeChat Community & Support' },
      { type: 'p', text: 'Portugal\'s Chinese community is concentrated in Lisbon\'s Mouraria and Martim Moniz areas. The China-Portugal Chamber of Commerce provides business support. Many notaries, lawyers and accountants in Lisbon offer Mandarin services. Agency Group can provide introductions.' },
      { type: 'cta', text: 'Agency Group offers English and Mandarin support for Chinese buyers. We specialise in structuring Golden Visa-compliant acquisitions.' },
    ],
  },

  // ─────────────────────────────────────────────
  // LEGAL / VISTOS (4)
  // ─────────────────────────────────────────────
  {
    slug: 'visto-d7-portugal-guia-completo',
    title: 'Visto D7 Portugal 2026: O Guia Completo para Obter Residência',
    description: 'Como obter o Visto D7 de Rendimentos Passivos em Portugal em 2026: requisitos, documentação, prazo e como combinar com o NHR/IFICI.',
    category: 'Vistos & Legal',
    date: '2026-01-10',
    author: 'Agency Group',
    readingTime: 11,
    keywords: ['visto d7 portugal', 'residência portugal rendimentos passivos', 'como obter d7 portugal 2026'],
    content: [
      { type: 'intro', text: 'O Visto D7 (Visto de Residência para Titulares de Rendimentos de Fonte Estrangeira) é hoje o caminho mais popular para estrangeiros que desejam residir em Portugal. Sem exigência de investimento mínimo, disponível para qualquer nacionalidade e com processo relativamente simples, é a porta de entrada ideal para reformados, investidores e nómadas digitais.' },
      { type: 'h2', text: 'Quem Pode Requerer o D7' },
      { type: 'ul', items: ['Reformados com pensão de qualquer país', 'Investidores com rendimentos de arrendamento, dividendos ou mais-valias', 'Trabalhadores freelance ou com contrato de trabalho remoto', 'Titulares de rendimentos passivos suficientes e regulares', 'Qualquer nacionalidade (não exclusivo a UE/EEE)'] },
      { type: 'h2', text: 'Rendimento Mínimo Exigido 2026' },
      { type: 'table', headers: ['Composição do Agregado', 'Rendimento Mensal Mínimo'], rows: [['Titular (sozinho)', '€760/mês (salário mínimo PT)'], ['Titular + cônjuge', '€760 + €380 = €1.140/mês'], ['+ 1 filho menor', '+€228/mês por dependente'], ['Rendimento anual mínimo solo', '€9.120/ano']] },
      { type: 'h2', text: 'Documentação Necessária' },
      { type: 'ul', items: ['Passaporte válido (min. 3 meses além do visto requerido)', 'Prova de rendimentos: extractos bancários 3 meses, declarações fiscais, pensão, contrato de arrendamento', 'NIF português (obtenção prévia obrigatória)', 'Prova de alojamento em Portugal: contrato de arrendamento ou título de propriedade', 'Seguro de saúde válido em Portugal (viagem ou saúde internacional)', 'Certificado de antecedentes criminais do país de residência (apostilado)', 'Formulário de candidatura preenchido'] },
      { type: 'h2', text: 'Processo e Prazos em 2026' },
      { type: 'p', text: 'O D7 requer candidatura no consulado português do país de residência. Prazo médio de aprovação: 60–90 dias. Após aprovação, entrada em Portugal e agendamento com AIMA para emissão da Autorização de Residência (AR). AR inicial: 2 anos. Renovação por 3 anos. Após 5 anos: elegível para Residência Permanente ou Naturalização.' },
      { type: 'highlight', label: 'Combinar com NHR/IFICI', text: 'O D7 é perfeitamente compatível com o regime NHR/IFICI. Ao registar residência em Portugal e candidatar-se ao IFICI no mesmo ano fiscal, pode beneficiar de taxa reduzida de 20% em IRS (rendimentos de trabalho qualificado em Portugal) durante 10 anos.' },
      { type: 'cta', text: 'A Agency Group trabalha com advogados de imigração especializados em D7. Consultoria inicial gratuita.' },
    ],
  },
  {
    slug: 'golden-visa-portugal-2026-guia',
    title: 'Golden Visa Portugal 2026: Guia Actualizado ARI',
    description: 'Estado actual do Golden Visa (ARI) em Portugal em 2026: o que mudou, quais investimentos ainda qualificam e como candidatar.',
    category: 'Vistos & Legal',
    date: '2026-01-17',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['golden visa portugal 2026', 'ARI portugal residência investimento', 'golden visa portugal imóvel'],
    content: [
      { type: 'intro', text: 'O Golden Visa português — formalmente ARI (Autorização de Residência para Investimento) — passou por reformas significativas em 2023/2024. Em 2026, a compra directa de imóvel residencial em Lisboa, Porto ou Algarve já não qualifica, mas existem alternativas igualmente atraentes.' },
      { type: 'h2', text: 'O Que Qualifica em 2026' },
      { type: 'table', headers: ['Tipo de Investimento', 'Montante Mínimo', 'Notas'], rows: [['Fundos de investimento qualificados', '€500.000', 'Opção mais popular em 2026'], ['Actividade de investigação científica', '€500.000', 'Via entidades reconhecidas'], ['Criação de 10 empregos permanentes', 'N/A', 'Complexo na prática'], ['Arte / Património cultural', '€250.000', 'Via entidade cultural reconhecida'], ['Imóvel em zonas interiores / ilhas', '€500.000', 'Madeira, Açores, interior continental']] },
      { type: 'h2', text: 'Vantagens do Golden Visa em 2026' },
      { type: 'ul', items: ['Residência portuguesa válida em todos os países Schengen', 'Exige apenas 7 dias de presença física em Portugal por ano', 'Após 5 anos: elegível para Residência Permanente', 'Após 5 anos: elegível para Naturalização Portuguesa (passaporte EU)', 'Família incluída: cônjuge e filhos menores incluídos na candidatura', 'Compatível com NHR/IFICI se em Portugal >183 dias/ano'] },
      { type: 'h2', text: 'Fundos de Investimento: A Rota Mais Escolhida' },
      { type: 'p', text: 'Em 2026, os fundos de capital de risco e fundos imobiliários qualificados são a rota preferida para a maioria dos candidatos ao Golden Visa. Existem mais de 40 fundos aprovados com estratégias diversas (imobiliário, tecnologia, turismo). Retornos projetados de 4–8% a.a. na maioria dos fundos imobiliários.' },
      { type: 'cta', text: 'A Agency Group indica advogados de imigração especializados e os melhores fundos qualificados para Golden Visa. Consulte-nos gratuitamente.' },
    ],
  },
  {
    slug: 'nhr-ifici-portugal-guia-fiscal',
    title: 'NHR / IFICI Portugal 2026: O Guia Fiscal Definitivo',
    description: 'Como funciona o regime NHR (agora IFICI) em Portugal em 2026: quem qualifica, como candidatar, benefícios e comparação com NHR antigo.',
    category: 'Vistos & Legal',
    date: '2026-01-24',
    author: 'Agency Group',
    readingTime: 12,
    keywords: ['nhr portugal 2026', 'IFICI portugal imposto', 'regime fiscal favorável portugal expatriados'],
    content: [
      { type: 'intro', text: 'O NHR (Residente Não Habitual) foi substituído em Janeiro 2024 pelo IFICI (Incentivo Fiscal à Investigação Científica e Inovação). O novo regime é mais restrito mas mantém benefícios fiscais substanciais para os que qualificam — uma taxa flat de 20% em IRS sobre rendimentos de trabalho qualificado em Portugal.' },
      { type: 'h2', text: 'IFICI vs NHR: Principais Diferenças' },
      { type: 'table', headers: ['Aspecto', 'NHR (2009–2023)', 'IFICI (2024+)'], rows: [['Actividades elegíveis', 'Qualquer actividade de "alto valor acrescentado"', 'Investigação, tecnologia, inovação, específicas'], ['Taxa sobre rendimentos PT', '20% flat', '20% flat (mesma)'], ['Pensões estrangeiras', 'Taxa 10% (após 2020)', 'Não elegível'], ['Rendimentos estrangeiros', 'Isenção em muitos casos', 'Isenção em alguns casos'], ['Duração', '10 anos', '10 anos'], ['Quem qualifica', 'Amplo', 'Restrito a actividades específicas']] },
      { type: 'h2', text: 'Actividades Elegíveis para IFICI' },
      { type: 'ul', items: ['I&D (investigação e desenvolvimento) em entidade portuguesa qualificada', 'Trabalhadores qualificados em empresas de tecnologia e inovação', 'Professores e investigadores em universidades portuguesas', 'Start-up founders registados em Portugal', 'Trabalhadores com licenciatura em áreas STEM contratados por empresas exportadoras', 'Gestores de fundos de investimento qualificados'] },
      { type: 'h2', text: 'Como Candidatar ao IFICI' },
      { type: 'ul', items: ['Obter NIF e tornar-se residente fiscal em Portugal (183+ dias ou habitação permanente)', 'Verificar elegibilidade da actividade com fiscalista português', 'Submeter declaração na AT (Autoridade Tributária) no início do ano fiscal', 'Declaração aceite: taxa de 20% aplicada retroactivamente ao ano inteiro'] },
      { type: 'h2', text: 'Exemplo de Poupança Fiscal IFICI vs Regime Geral' },
      { type: 'p', text: 'Engenheiro de software com rendimento tributável de €150.000/ano em Portugal: Regime geral → ~€58.000 em IRS. IFICI → €30.000 em IRS (20%). Poupança: €28.000/ano × 10 anos = €280.000 de diferença acumulada. O IFICI é um dos regimes fiscais mais favoráveis da União Europeia.' },
      { type: 'cta', text: 'Quer saber se a sua actividade profissional qualifica para o IFICI? A Agency Group indica fiscalistas especializados em expatriados.' },
    ],
  },
  {
    slug: 'cpcv-escritura-processo-legal-compra-imovel',
    title: 'CPCV e Escritura: O Processo Legal Completo na Compra de Imóvel',
    description: 'Guia completo sobre o processo legal de compra de imóvel em Portugal: due diligence, CPCV, IMT, escritura e registo predial.',
    category: 'Vistos & Legal',
    date: '2026-02-01',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['cpcv compra imóvel portugal', 'escritura compra casa processo', 'processo legal compra imóvel portugal'],
    content: [
      { type: 'intro', text: 'A compra de um imóvel em Portugal segue um processo jurídico bem definido com duas fases principais: o CPCV (Contrato-Promessa de Compra e Venda) e a Escritura Pública de Compra e Venda. Conhecer cada etapa protege o comprador e evita surpresas desagradáveis.' },
      { type: 'h2', text: 'Fase 1: Due Diligence (Antes do CPCV)' },
      { type: 'ul', items: ['Certidão Predial Permanente: historial do imóvel, ónus, hipotecas, penhoras', 'Caderneta Predial Urbana: área fiscal, matriz, valor patrimonial tributário (VPT)', 'Licença de Utilização / Habitabilidade: confirmar que o imóvel tem licença válida para habitação', 'Ficha Técnica de Habitação: obrigatória para imóveis construídos após 30/03/2004', 'Certificado Energético: obrigatório para anunciar e vender', 'Certidão de Não Dívida de Condomínio: confirmar ausência de dívidas ao condomínio'] },
      { type: 'h2', text: 'Fase 2: CPCV — Pontos Críticos' },
      { type: 'ul', items: ['Sinal habitual: 10–30% do preço de compra', 'Cláusula penal: se vendedor incumpre → devolve sinal em dobro. Se comprador incumpre → perde sinal', 'Data de escritura: definir prazo razoável (60–90 dias típico)', 'Condição suspensiva: incluir se sujeito a aprovação de financiamento', 'Identificação precisa do imóvel: artigo matricial, confrontações, área', 'Estado do imóvel: cláusula "no estado actual" ou com lista de obras a realizar pelo vendedor'] },
      { type: 'h2', text: 'Fase 3: Escritura Pública' },
      { type: 'p', text: 'A escritura é celebrada perante notário, com apresentação de todos os documentos de due diligence + pagamento de IMT e IS (antes da data de escritura). O notário verifica identidades, lê o contrato em voz alta e todos os outorgantes assinam. Duração típica: 30–60 minutos.' },
      { type: 'h2', text: 'Fase 4: Registo Predial' },
      { type: 'p', text: 'Após escritura, o notário submete electronicamente o pedido de registo predial. O registo é actualizado em 1–3 dias úteis (ou no próprio dia com registo urgente, €150 extra). Só após o registo o comprador é juridicamente o proprietário perante terceiros.' },
      { type: 'highlight', label: 'Custos Totais da Transacção', text: 'Para imóvel de €500.000: IMT €27.500 + IS €4.000 + Notário €1.500 + Registo €300 + Advogado €2.500–€5.000 = Total ~€35.800–€38.300 (7,2–7,7% do preço).' },
      { type: 'cta', text: 'A Agency Group acompanha compradores em todo o processo legal, desde a due diligence à entrega das chaves.' },
    ],
  },

  // ─────────────────────────────────────────────
  // MERCADO / TENDÊNCIAS (6)
  // ─────────────────────────────────────────────
  {
    slug: 'relatorio-mercado-imobiliario-portugal-2026',
    title: 'Relatório do Mercado Imobiliário Português 2026: Análise Completa',
    description: 'Análise aprofundada do mercado imobiliário português em 2026: preços, volumes, tendências, segmento de luxo e previsões 2027.',
    category: 'Mercado',
    date: '2026-01-05',
    author: 'Agency Group',
    readingTime: 14,
    keywords: ['mercado imobiliário portugal 2026', 'preços imóveis portugal 2026', 'relatório imobiliário portugal'],
    content: [
      { type: 'intro', text: 'O mercado imobiliário português entrou em 2026 em pleno momentum ascendente. Com 169.812 transacções em 2025, crescimento de preços de 17,6% e Lisboa no top 5 mundial de luxo (Knight Frank Prime Cities Index), Portugal consolida-se como um dos mercados mais dinâmicos da Europa Ocidental.' },
      { type: 'h2', text: 'Números-Chave do Mercado 2025/2026' },
      { type: 'table', headers: ['Indicador', 'Valor 2025', 'Variação vs 2024'], rows: [['Transacções totais', '169.812', '+8,3%'], ['Preço mediana nacional', '€3.076/m²', '+17,6%'], ['Volume total transaccionado', '€42,1 mil milhões', '+27%'], ['Tempo médio de venda', '210 dias', '−15 dias'], ['Crédito habitação concedido', '€18,4 mil milhões', '+22%']] },
      { type: 'h2', text: 'Lisboa: Top 5 Mundial no Luxo' },
      { type: 'p', text: 'O Prime Residential Index da Knight Frank posiciona Lisboa em 5º lugar mundial em crescimento de preços no segmento ultra-premium (€5M+), com +19,3% em 2025. Acima de Dubai (+22%) mas abaixo apenas de Miami (+24%), Nova York e Singapura. Dados atribuem o crescimento à combinação de escassez de oferta, procura internacional intensa e qualidade de vida única.' },
      { type: 'h2', text: 'Drivers de Procura 2026' },
      { type: 'ul', items: ['NHR/IFICI: continua a atrair executivos e trabalhadores tech europeus e americanos', 'Fluxo migratório positivo: saldo migratório de +89.000 em 2025 — máximo histórico', 'Nómadas digitais: 22.000 novos vistos D8 emitidos em 2025', 'Turbulência geopolítica: Portugal como "safe haven" para HNWI de Europa Central e Médio Oriente', 'Juros em queda: Euribor de 4,1% (pico 2023) para 2,1% (Março 2026) — renovação da procura de financiamento'] },
      { type: 'h2', text: 'Constrangimentos de Oferta' },
      { type: 'ul', items: ['Licenciamento lento: prazo médio de 24 meses em Lisboa para novas obras', 'Escassez de mão-de-obra na construção: salários de construção subiram 18% em 2025', 'Custos de construção: materiais +12% em 2025 (aço, alumínio, cimento)', 'Parque habitacional envelhecido: 34% dos edifícios têm mais de 50 anos — reabilitação como alternativa', 'Solo urbanizável escasso nas áreas metropolitanas de Lisboa e Porto'] },
      { type: 'h2', text: 'Previsão para 2027' },
      { type: 'p', text: 'O consenso de analistas (JLL, Savills, CBRE, BNP Paribas RE) aponta para crescimento de preços de 10–14% em 2026 e 8–12% em 2027. A combinação de procura estrutural robusta com oferta cronicamente limitada suporta a tese de valorização a médio prazo. Risco principal: arrefecimento económico global e subida inesperada das taxas.' },
      { type: 'cta', text: 'Receba o Relatório Mercado 2026 completo da Agency Group — 52 páginas de análise proprietária para investidores.' },
    ],
  },
  {
    slug: 'tendencias-luxo-imobiliario-portugal-2026',
    title: 'Luxo Imobiliário em Portugal 2026: Tendências e Mercado Ultra-Premium',
    description: 'O segmento de luxo imobiliário em Portugal em 2026: quem compra, o que compra, preços recorde e as zonas mais exclusivas.',
    category: 'Mercado',
    date: '2026-01-31',
    author: 'Agency Group',
    readingTime: 11,
    keywords: ['luxo imobiliário portugal', 'imóveis premium portugal 2026', 'mercado ultra-luxo lisboa'],
    content: [
      { type: 'intro', text: 'O segmento de ultra-luxo em Portugal (€5M+) bateu todos os recordes em 2025, com 287 transacções acima dos €5M — 34% mais do que em 2024. Lisboa e Cascais dominam, mas Comporta e o Algarve surgem com transacções cada vez mais elevadas. O que está a acontecer no topo do mercado?' },
      { type: 'h2', text: 'Perfil do Comprador de Luxo em Portugal 2026' },
      { type: 'table', headers: ['Perfil', '%', 'Ticket Médio', 'Zonas Preferidas'], rows: [['HNWI Norte-americano', '21%', '€4,2M', 'Lisboa, Cascais, Algarve'], ['Family Office europeu', '18%', '€7,8M', 'Lisboa CBD, Quintas'], ['UHNWI Médio Oriente', '14%', '€9,1M', 'Cascais, Comporta, Algarve'], ['Tech exec / entrepreneur', '12%', '€2,8M', 'Lisboa, Porto'], ['Comprador HNWI brasileiro', '8%', '€1,9M', 'Lisboa, Algarve']] },
      { type: 'h2', text: 'O Que Define "Luxo" em Portugal em 2026' },
      { type: 'ul', items: ['Localização: primeira linha de rio/mar, address histórico (Chiado, Príncipe Real, Avenida da Liberdade)', 'Singularidade: palácio do século XVIII, penthouse com terraço de 500m², quinta histórica', 'Privacidade: murado, discrito, sem vizinhos imediatos — especialmente valorizado pelos compradores de Médio Oriente', 'Sustentabilidade: LEED, certificado A+ energético, painéis solares — diferenciador crescente para compradores nórdicos e americanos', 'Serviços: consierge, segurança 24h, spa, heliponto (em casos específicos)'] },
      { type: 'h2', text: 'Recordes de Transacção em 2025' },
      { type: 'p', text: 'O imóvel mais caro transaccionado em Portugal em 2025 foi uma Herdade no Alentejo (800 hectares, turismo rural de luxo): €38 milhões. Em Lisboa, o apartamento mais caro (Chiado duplex, 650m², terraço panorâmico) fechou a €12,4M (€19.077/m²). Em Cascais (Quinta da Marinha, villa 1.200m² hab.): €15,5M.' },
      { type: 'cta', text: 'A Agency Group opera exclusivamente no segmento premium. Portfolio privado de propriedades de luxo disponível para clientes qualificados.' },
    ],
  },
  {
    slug: 'arrendamento-curta-duracao-portugal-2026',
    title: 'Alojamento Local em Portugal 2026: Guia de Investimento e Regulação',
    description: 'Tudo sobre Alojamento Local (AL) em Portugal em 2026: licenças, regimes de suspensão, yields e como maximizar retorno do Airbnb.',
    category: 'Mercado',
    date: '2026-02-07',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['alojamento local portugal 2026', 'airbnb portugal licença', 'investimento al portugal yields'],
    content: [
      { type: 'intro', text: 'O Alojamento Local em Portugal é o tema mais controverso do imobiliário nacional. Entre restrições em Lisboa e Porto, crescimento explosivo no Algarve e em zonas interiores, e yields acima de 6% para operadores profissionais, o AL continua a ser uma das mais atractivas estratégias de investimento — se bem estruturado.' },
      { type: 'h2', text: 'Enquadramento Legal em 2026' },
      { type: 'ul', items: ['Zonas de contenção: Lisboa e Porto têm suspensão de novas licenças AL nas freguesias centrais. Renovação de licenças existentes: automática', 'NUTS III onde se inserem: municípios com mais de 75% de AL no total do parque habitacional podem suspender novas licenças', 'Algarve: sem suspensão geral, mas municípios podem definir localmente', 'Açores e Madeira: sem restrições de contenção', 'Condomínios: assembleia de condóminos pode opor-se por maioria de ⅔'] },
      { type: 'h2', text: 'Yields por Zona e Tipo de Operação' },
      { type: 'table', headers: ['Zona', 'ADR Médio', 'Ocupação Est.', 'Yield Bruto'], rows: [['Lisboa Centro (com licença)', '€145/noite', '72%', '5,5–7%'], ['Porto Ribeira', '€118/noite', '75%', '6–7,5%'], ['Algarve Vilamoura', '€170/noite', '65%', '5,5–7%'], ['Comporta', '€380/noite', '58%', '4,5–6%'], ['Madeira Funchal', '€105/noite', '68%', '5–6,5%'], ['Açores São Miguel', '€88/noite', '62%', '4,8–6%']] },
      { type: 'h2', text: 'Tributação do AL em 2026' },
      { type: 'p', text: 'Rendimentos de AL são tributados como Categoria B (actividade empresarial e profissional). Regime simplificado: coeficiente de 35% (65% presumido de despesas). Regime de contabilidade organizada: despesas reais dedutíveis. Para operações acima de €200K/ano, a constituição de empresa pode oferecer vantagens fiscais (IRC 21% vs escalão marginal IRS).' },
      { type: 'cta', text: 'A Agency Group identifica propriedades com licença AL em Lisboa e Porto — os activos mais escassos e valorizados do mercado. Consulte-nos.' },
    ],
  },
  {
    slug: 'reabilitacao-urbana-portugal-oportunidade',
    title: 'Reabilitação Urbana em Portugal: A Grande Oportunidade de 2026',
    description: 'Como investir em reabilitação urbana em Portugal: incentivos fiscais, IFRRU, PME Crescimento, margens de promoção e melhores zonas.',
    category: 'Mercado',
    date: '2026-02-21',
    author: 'Agency Group',
    readingTime: 10,
    keywords: ['reabilitação urbana portugal', 'investimento reabilitação imóvel', 'IFRRU reabilitação urbana portugal'],
    content: [
      { type: 'intro', text: 'Com 34% do parque habitacional português com mais de 50 anos e centros históricos de Lisboa e Porto ainda com edifícios devolutos, a reabilitação urbana é a maior oportunidade estrutural do imobiliário português. Incentivos fiscais generosos e financiamento específico (IFRRU) tornam a equação altamente favorável.' },
      { type: 'h2', text: 'Incentivos Fiscais para Reabilitação' },
      { type: 'ul', items: ['IVA a 6%: em vez dos 23% standard para obras de reabilitação em imóveis com mais de 30 anos', 'IMI 0% durante 3 anos: após obras de reabilitação em Áreas de Reabilitação Urbana (ARU)', 'IMT 0%: em aquisições de imóveis para reabilitação em ARU (isenção total)', 'Mais-valias: taxa reduzida de 5% para imóveis em ARU vendidos após reabilitação (vs 28% standard)', 'Deduções IRS: 30% das despesas de conservação (máx €500/ano) em imóveis arrendados em AR'] },
      { type: 'h2', text: 'IFRRU 2020+: Financiamento Específico' },
      { type: 'p', text: 'O Instrumento Financeiro para a Reabilitação e Revitalização Urbanas (IFRRU) oferece empréstimos a taxas bonificadas (1–2% a.a.) para reabilitação de edifícios em ARU. Montante máximo: €2,5M. Prazo: até 30 anos. Disponível via CGD, Millennium BCP e outros bancos parceiros.' },
      { type: 'h2', text: 'Margens de Promoção em Reabilitação 2026' },
      { type: 'table', headers: ['Zona', 'Custo Aquisição+Obra €/m²', 'Venda Estimada €/m²', 'Margem Bruta'], rows: [['Lisboa Bairros Históricos', '€3.200–€4.500', '€5.500–€8.000', '30–45%'], ['Porto Bonfim / Campanhã', '€1.800–€2.800', '€3.200–€4.500', '40–55%'], ['Porto Ribeira / Cedofeita', '€2.500–€3.500', '€4.000–€5.500', '35–50%'], ['Madeira Centro Funchal', '€2.000–€3.000', '€3.500–€5.500', '40–50%']] },
      { type: 'cta', text: 'A Agency Group identifica edifícios devolutos com potencial de reabilitação em Lisboa e Porto. Portfolio exclusivo disponível.' },
    ],
  },
  {
    slug: 'sustentabilidade-imoveis-portugal-esg',
    title: 'Sustentabilidade e ESG no Imobiliário Português 2026',
    description: 'Como a sustentabilidade está a transformar o imobiliário em Portugal: certificações, prémio verde, exigências da UE e como posicionar investimentos.',
    category: 'Mercado',
    date: '2026-02-28',
    author: 'Agency Group',
    readingTime: 8,
    keywords: ['sustentabilidade imobiliário portugal', 'ESG imóveis portugal', 'certificação energética imóvel portugal'],
    content: [
      { type: 'intro', text: 'A agenda ESG chegou ao imobiliário português com força em 2025/2026. Directivas europeias de eficiência energética (EPBD), exigências dos investidores institucionais e um mercado comprador crescentemente consciente criaram um "prémio verde" real nos imóveis com certificação energética elevada.' },
      { type: 'h2', text: 'O Prémio Verde em Portugal em 2026' },
      { type: 'ul', items: ['Imóveis A+/A: vendem 8–14% acima de imóveis equivalentes com certificado D/E', 'Arrendamento: rendas de imóveis A/A+ são 12–18% superiores ao mercado geral', 'Tempo de venda: imóveis A+ vendem 35 dias mais rápido em média', 'Financiamento: bancos oferecem "green mortgage" com spread 0,15–0,25% inferior para imóveis A+'] },
      { type: 'h2', text: 'EPBD: O Que Muda até 2030' },
      { type: 'p', text: 'A Directiva Europeia de Desempenho Energético dos Edifícios (EPBD 2024) obriga a que todos os edifícios residenciais na UE atinjam pelo menos classe energética E até 2030 e D até 2033. Em Portugal, estima-se que 42% do parque habitacional actual precise de obras de melhoria energética — uma oportunidade massiva de reabilitação.' },
      { type: 'h2', text: 'Como Melhorar a Certificação Energética' },
      { type: 'ul', items: ['Isolamento da cobertura e paredes: ganho médio de 2 classes energéticas', 'Substituição de janelas por vidro duplo com caixilharia térmica: +1 classe', 'Bomba de calor aerotérmica para AQS: +1–2 classes', 'Painéis solares fotovoltaicos: +1–2 classes + geração de receita', 'Custos típicos: €8.000–€25.000 para upgrade D→A em apartamento padrão'] },
      { type: 'cta', text: 'A Agency Group analisa o potencial de valorização ESG de cada imóvel e recomenda as obras de maior impacto no valor de venda.' },
    ],
  },
  {
    slug: 'tendencias-tecnologia-imobiliario-proptech',
    title: 'PropTech e Tecnologia no Imobiliário Português 2026',
    description: 'Como a tecnologia está a transformar o mercado imobiliário em Portugal: PropTech, AVM, visitas virtuais, IA e o futuro da compra de casa.',
    category: 'Mercado',
    date: '2026-03-07',
    author: 'Agency Group',
    readingTime: 8,
    keywords: ['proptech portugal', 'tecnologia imobiliária portugal', 'inteligência artificial imóveis portugal'],
    content: [
      { type: 'intro', text: 'O sector imobiliário português, historicamente conservador, está a viver uma revolução tecnológica. De AVMs baseados em IA a visitas virtuais com Matterport, de assinatura digital de CPCV a due diligence automatizada, as transacções imobiliárias de 2026 são radicalmente diferentes das de 2019.' },
      { type: 'h2', text: 'PropTech em Portugal: Estado da Arte 2026' },
      { type: 'ul', items: ['AVM (Automated Valuation Models): múltiplos players — Casa Sapo AVM, Imovirtual AVM, Agency Group AVM (47 variáveis, precisão de ±8%)', 'Visitas virtuais 360° / Matterport: 78% dos anúncios premium incluem já tour virtual em 2026', 'Assinatura digital CPCV: legalmente válida em Portugal desde 2020 — adopção atingiu 45% dos contratos em 2025', 'Due diligence automatizada: Certidão Predial, Caderneta, Certificado Energético disponíveis em APIs', 'CRM com IA: scoring de leads, previsão de conversão, nudge timing optimizado'] },
      { type: 'h2', text: 'Inteligência Artificial na Mediação Imobiliária' },
      { type: 'p', text: 'A Agency Group usa IA proprietária (Deal Radar) para identificar as melhores oportunidades de mercado em tempo real, cruzando 23 fontes de dados incluindo portais, registos do IMI, licenças de obras e dados de escrituras. O sistema identifica imóveis subvalorizados até 30 dias antes de aparecerem nos portais generalistas.' },
      { type: 'h2', text: 'O Futuro: O Que Vem a Seguir' },
      { type: 'ul', items: ['Tokenização imobiliária: fraccionamento de propriedades via tokens blockchain — em testes em Portugal em 2026', 'Escrituras completamente digitais: projecto-piloto AT/IRN em curso para 2027', 'Avaliações bancárias por IA: BdP em consulta sobre framework de AVMs para crédito habitação', 'Proptech de gestão: plataformas de property management conectadas a sensores IoT — eficiência energética em tempo real'] },
      { type: 'cta', text: 'A Agency Group está na vanguarda da tecnologia imobiliária em Portugal. Experimente o nosso AVM e Deal Radar.' },
    ],
  },
]

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find(a => a.slug === slug)
}

export function getRelatedArticles(article: Article, count = 3): Article[] {
  return ARTICLES
    .filter(a => a.slug !== article.slug && (a.category === article.category || a.zona === article.zona))
    .slice(0, count)
}
