-- Agency Group · Supabase Migration 002 · Seed Properties
-- Inserts all 20 core portfolio properties

INSERT INTO properties (
  id, nome, zona, bairro, tipo, preco, area, quartos, casas_banho,
  energia, descricao, features, badge, status, lifestyle_tags, gradient
) VALUES

-- ─── LISBOA ──────────────────────────────────────────────────────────────────
(
  'AG-2026-010',
  'Penthouse Príncipe Real',
  'Lisboa',
  'Príncipe Real',
  'Penthouse',
  2850000,
  220,
  3,
  3,
  'A',
  'Penthouse exclusiva no coração do Príncipe Real. Piso 6 com terraço privativo de 80m², vistas 360° sobre Lisboa e o Tejo. Acabamentos de luxo, cozinha Bulthaup, domótica completa.',
  '["Terraço 80m²", "Vistas Tejo", "Domótica", "Cozinha Bulthaup", "Piscina privativa", "Garagem dupla", "Arrecadação", "Condomínio seguro"]',
  'Destaque',
  'active',
  '["Luxo", "Vista Mar", "Lifestyle Urbano", "Investimento Premium"]',
  'linear-gradient(135deg, #1a3a2a 0%, #0c1f15 100%)'
),
(
  'AG-2026-011',
  'Apartamento Chiado Premium',
  'Lisboa',
  'Chiado',
  'Apartamento',
  1450000,
  145,
  2,
  2,
  'A+',
  'T2 remodelado no Chiado, o bairro mais cosmopolita de Lisboa. Andar alto com vista para o Rio Tejo. Acabamentos premium, tectos altos, recuperador de calor.',
  '["Andar alto", "Vista Tejo", "Remodelado 2024", "Recuperador calor", "Parquet original", "Garagem", "Elevador", "Porteiro"]',
  'Novo',
  'active',
  '["Lifestyle Cultural", "Gastronomia", "Passeios a Pé", "Arrendamento Premium"]',
  'linear-gradient(135deg, #2a1a3a 0%, #1a0c2a 100%)'
),
(
  'AG-2026-012',
  'Moradia Belém com Jardim',
  'Lisboa',
  'Belém',
  'Moradia',
  3200000,
  380,
  5,
  4,
  'A',
  'Moradia independente em Belém com jardim privado de 600m². Arquitectura contemporânea, piscina aquecida, garagem tripla. A 5 minutos do Museu dos Coches e da Torre de Belém.',
  '["Jardim 600m²", "Piscina aquecida", "Garagem tripla", "Home cinema", "Escritório", "Sala de jogos", "Painéis solares", "Barbecue exterior"]',
  'Off-Market',
  'active',
  '["Família", "Luxo Discreto", "Lifestyle Heritage", "Jardim Privado"]',
  'linear-gradient(135deg, #1a2a3a 0%, #0c1a2a 100%)'
),
(
  'AG-2026-013',
  'Apartamento Campo de Ourique',
  'Lisboa',
  'Campo de Ourique',
  'Apartamento',
  780000,
  110,
  3,
  2,
  'B',
  'T3 em Campo de Ourique, o bairro mais residencial e familiar de Lisboa. Andar 3 com varanda, estacionamento, arrecadação. Ideal para habitação própria ou investimento.',
  '["Varanda", "Estacionamento", "Arrecadação", "Bairro residencial", "Mercado de Campo de Ourique", "Metro Rato a 5min"]',
  'Novo',
  'active',
  '["Família", "HPP", "Bairro Residencial", "Bom para Arrendamento"]',
  'linear-gradient(135deg, #2a2a1a 0%, #1a1a0c 100%)'
),

-- ─── CASCAIS ─────────────────────────────────────────────────────────────────
(
  'AG-2026-020',
  'Villa Quinta da Marinha',
  'Cascais',
  'Quinta da Marinha',
  'Villa',
  3800000,
  450,
  5,
  5,
  'A',
  'Villa de arquitectura contemporânea na Quinta da Marinha, em frente ao campo de golfe. Piscina infinity, jardim paisagístico, domótica integral. A 500m da praia do Guincho.',
  '["Piscina infinity", "Campo Golfe fronteira", "Jardim paisagístico", "Garagem tripla", "Sala cinema", "Jacuzzi exterior", "Painéis solares", "Alarme 24h"]',
  'Exclusivo',
  'active',
  '["Golf Lifestyle", "Praia Guincho", "Luxo Contemporâneo", "Família Internacional"]',
  'linear-gradient(135deg, #1a3a1a 0%, #0c2a0c 100%)'
),
(
  'AG-2026-021',
  'Moradia Estoril Frente Mar',
  'Cascais',
  'Estoril',
  'Moradia',
  2100000,
  280,
  4,
  3,
  'A',
  'Moradia com acesso directo à praia do Estoril. Terraço sobre o mar, piscina aquecida, jardim privado. Arquitetura dos anos 50 remodelada com materiais premium. A 2 minutos a pé do Casino.',
  '["Frente mar", "Acesso praia privada", "Piscina aquecida", "Terraço", "Jardim 400m²", "Garagem dupla", "Cave adega", "Remodelada 2023"]',
  'Destaque',
  'active',
  '["Vista Mar", "Lifestyle Costeiro", "Herança Arquitectónica", "Praia a Pé"]',
  'linear-gradient(135deg, #1a3a3a 0%, #0c2a2a 100%)'
),
(
  'AG-2026-022',
  'Apartamento Cascais Centro',
  'Cascais',
  'Cascais Centro',
  'Apartamento',
  650000,
  95,
  2,
  2,
  'A',
  'T2 moderno no centro histórico de Cascais. A 3 minutos da baía. Condomínio com piscina, ginásio e concierge 24h. Ideal para NHR ou investimento turístico.',
  '["Piscina condomínio", "Ginásio", "Concierge 24h", "3min da Baía", "Varandas", "Box garagem"]',
  'Novo',
  'active',
  '["NHR", "Investimento Turístico", "Lifestyle Costeiro", "Gestão de Arrendamento"]',
  'linear-gradient(135deg, #3a2a1a 0%, #2a1a0c 100%)'
),

-- ─── COMPORTA ────────────────────────────────────────────────────────────────
(
  'AG-2026-030',
  'Herdade Comporta Exclusiva',
  'Comporta',
  'Comporta',
  'Herdade',
  6500000,
  850,
  6,
  6,
  'A+',
  'Herdade exclusiva na Comporta com 5 hectares de pinhal e acesso directo à praia. Casa principal de 850m² com arquitectura vernacular contemporânea, 4 suites, piscina natural. Off-market.',
  '["5 hectares", "Praia privada", "Piscina natural biológica", "4 suites master", "Adega vinhos", "Cavalariça", "Casa dos caseiros", "Heliponto autorizado"]',
  'Off-Market',
  'active',
  '["Ultra Luxo", "Off-Market", "Família HNWI", "Praia Privada", "Natureza"]',
  'linear-gradient(135deg, #3a3a1a 0%, #2a2a0c 100%)'
),
(
  'AG-2026-031',
  'Villa Carvalhal Comporta',
  'Comporta',
  'Carvalhal',
  'Villa',
  1850000,
  320,
  4,
  4,
  'A',
  'Villa contemporânea no Carvalhal, a 500m da praia. Design arquitetónico assinado, madeira e pedra local. Piscina infinita, jardim com dunas naturais. Licença AL activa.',
  '["500m da praia", "Piscina infinita", "Licença AL activa", "Dunas naturais", "Deck madeira", "Garagem 2 carros", "Churrasqueira exterior"]',
  'Exclusivo',
  'active',
  '["Lifestyle Comporta", "Alojamento Local", "Rendimento", "Design Contemporâneo"]',
  'linear-gradient(135deg, #3a2a1a 0%, #2a1a0c 100%)'
),

-- ─── PORTO ───────────────────────────────────────────────────────────────────
(
  'AG-2026-040',
  'Apartamento Foz do Douro',
  'Porto',
  'Foz do Douro',
  'Apartamento',
  980000,
  180,
  3,
  2,
  'A',
  'T3 de luxo na Foz do Douro com vistas para o Oceano Atlântico. Condomínio premium, piscina, ginásio, box garagem dupla. O endereço mais exclusivo do Porto.',
  '["Vista Oceano", "Piscina condomínio", "Ginásio", "Box dupla", "Terraço", "Elevador", "Porteiro", "Andar 4"]',
  'Destaque',
  'active',
  '["Luxo Porto", "Vista Oceano", "Foz Premium", "Investimento Porto"]',
  'linear-gradient(135deg, #3a1a1a 0%, #2a0c0c 100%)'
),
(
  'AG-2026-041',
  'Penthouse Boavista Porto',
  'Porto',
  'Boavista',
  'Penthouse',
  1200000,
  195,
  3,
  3,
  'A+',
  'Penthouse na Boavista, o centro financeiro do Porto. Terraço privativo de 100m² com vista panorâmica. Domótica, acabamentos de luxo, garagem dupla. A 5 minutos da Casa da Música.',
  '["Terraço 100m²", "Vista panorâmica Porto", "Domótica", "Garagem dupla", "Casa da Música 5min", "Ginásio", "Condomínio seguro"]',
  'Novo',
  'active',
  '["Executivo Porto", "Luxo Contemporâneo", "Vista Panorâmica", "Business Hub"]',
  'linear-gradient(135deg, #1a1a3a 0%, #0c0c2a 100%)'
),
(
  'AG-2026-042',
  'Apartamento Cedofeita',
  'Porto',
  'Cedofeita',
  'Apartamento',
  420000,
  85,
  2,
  1,
  'B',
  'T2 remodelado em Cedofeita, o bairro mais criativo do Porto. Andar 2, varanda, arrecadação. Ideal para arrendamento de médio prazo ou NHR. Yield estimado 5.5%.',
  '["Remodelado 2024", "Varanda", "Bairro criativo", "Yield 5.5%", "AL autorizado", "Mobilado"]',
  'Novo',
  'active',
  '["Investimento Yield", "NHR", "Arrendamento", "Cedofeita Trendy"]',
  'linear-gradient(135deg, #2a1a3a 0%, #1a0c2a 100%)'
),

-- ─── ALGARVE ─────────────────────────────────────────────────────────────────
(
  'AG-2026-050',
  'Villa Vale do Lobo Golf',
  'Algarve',
  'Vale do Lobo',
  'Villa',
  4200000,
  480,
  5,
  5,
  'A+',
  'Villa de luxo em Vale do Lobo, a resort mais exclusiva do Algarve. Frente ao Royal Golf Course. Piscina infinity aquecida, jardim de 1000m², garagem para 4 carros.',
  '["Royal Golf fronteira", "Piscina infinity aquecida", "Jardim 1000m²", "Garagem 4 carros", "Cinema privado", "Spa interior", "Jacuzzi exterior", "Staff quarters"]',
  'Exclusivo',
  'active',
  '["Golf Premium", "Ultra Luxo", "Algarve Exclusivo", "Internacional HNWI"]',
  'linear-gradient(135deg, #3a2a1a 0%, #2a1a0c 100%)'
),
(
  'AG-2026-051',
  'Apartamento Vilamoura Marina',
  'Algarve',
  'Vilamoura',
  'Apartamento',
  890000,
  130,
  3,
  2,
  'A',
  'T3 premium com vista directa para a Marina de Vilamoura. Condomínio de luxo com piscina, SPA e segurança 24h. A 5 minutos da praia. Licença AL activa com gestão incluída.',
  '["Vista Marina", "Piscina condomínio", "SPA", "Segurança 24h", "Licença AL", "5min praia", "Garagem", "Mobilado premium"]',
  'Destaque',
  'active',
  '["Marina Lifestyle", "Algarve Luxo", "Rendimento AL", "Internacional"]',
  'linear-gradient(135deg, #1a3a3a 0%, #0c2a2a 100%)'
),

-- ─── MADEIRA ─────────────────────────────────────────────────────────────────
(
  'AG-2026-060',
  'Apartamento Funchal Prime',
  'Madeira',
  'Funchal',
  'Apartamento',
  980000,
  165,
  3,
  2,
  'A',
  'T3 de luxo no coração do Funchal, com vista deslumbrante sobre o Oceano Atlântico e a marina. Condomínio fechado com piscina aquecida e ginásio. Madeira é o novo Algarve.',
  '["Vista Oceano 180°", "Piscina aquecida", "Ginásio", "Marina a 5min", "Garagem dupla", "Terraço privativo", "Segurança 24h"]',
  'Destaque',
  'active',
  '["Madeira Premium", "Vista Oceano", "NHR Madeira", "Clima Eterno"]',
  'linear-gradient(135deg, #1a3a2a 0%, #0c2a1a 100%)'
),
(
  'AG-2026-061',
  'Villa Câmara de Lobos',
  'Madeira',
  'Câmara de Lobos',
  'Villa',
  1350000,
  280,
  4,
  3,
  'A',
  'Villa contemporânea em Câmara de Lobos, o penhasco mais fotografado do mundo. Vista sobre o Oceano e a aldeia piscatória. Piscina, jardim tropical, garagem dupla.',
  '["Vista penhasco Oceano", "Piscina", "Jardim tropical", "Garagem dupla", "Churchill Bay 5min", "Banana plantation view", "Arquitectura madeirense contemporânea"]',
  'Exclusivo',
  'active',
  '["Vista Oceânica Única", "Lifestyle Madeira", "Arquitectura Assinada", "Churchill Legacy"]',
  'linear-gradient(135deg, #2a3a1a 0%, #1a2a0c 100%)'
),

-- ─── SINTRA ──────────────────────────────────────────────────────────────────
(
  'AG-2026-070',
  'Quinta Histórica Sintra',
  'Sintra',
  'Sintra Vila',
  'Quinta',
  2800000,
  650,
  6,
  5,
  'D',
  'Quinta senhorial do século XVIII em Sintra Património da Humanidade UNESCO. Casa principal de 650m², 4 hectares de parque ajardinado, piscina, pomar, cavalariça.',
  '["UNESCO Heritage", "4 hectares", "Século XVIII", "Cavalariça", "Pomar", "Piscina", "Biblioteca histórica", "Adega", "Casa dos caseiros", "Furo de água"]',
  'Off-Market',
  'active',
  '["Heritage Histórico", "Sintra UNESCO", "Familia ou Boutique Hotel", "Exclusividade Única"]',
  'linear-gradient(135deg, #2a3a2a 0%, #1a2a1a 100%)'
),
(
  'AG-2026-071',
  'Moradia Colares Contemporânea',
  'Sintra',
  'Colares',
  'Moradia',
  1100000,
  260,
  4,
  3,
  'A+',
  'Moradia contemporânea em Colares, entre a Serra de Sintra e o Oceano. Arquitectura verde com BREEAM Excellent, piscina aquecida, painéis solares, jardim biodiverso.',
  '["BREEAM Excellent", "Serra Sintra views", "Piscina aquecida", "100% solar", "Jardim biodiverso", "Garagem dupla", "5min praia do Maçã", "Adega climatizada"]',
  'Novo',
  'active',
  '["Arquitectura Sustentável", "Serra e Mar", "EcoLuxo", "Localização Rara"]',
  'linear-gradient(135deg, #1a3a1a 0%, #0c2a0c 100%)'
),

-- ─── ERICEIRA ────────────────────────────────────────────────────────────────
(
  'AG-2026-080',
  'Apartamento Ericeira Surf',
  'Ericeira',
  'Ericeira',
  'Apartamento',
  450000,
  90,
  2,
  2,
  'A',
  'T2 moderno em Ericeira, a única World Surf Reserve da Europa. A 200m da Praia dos Ribeiros. Varanda com vista mar, garagem, arrecadação. Licença AL activa. Yield 6%+.',
  '["200m praia", "Vista mar parcial", "Licença AL activa", "Yield 6%+", "World Surf Reserve", "Varanda", "Garagem", "Mobilado"]',
  'Novo',
  'active',
  '["Surf Lifestyle", "World Surf Reserve", "Investimento Yield", "Digital Nomad"]',
  'linear-gradient(135deg, #1a2a3a 0%, #0c1a2a 100%)'
),
(
  'AG-2026-081',
  'Villa Mafra Alto Luxo',
  'Ericeira',
  'Mafra',
  'Villa',
  1650000,
  350,
  5,
  4,
  'A',
  'Villa contemporânea em Mafra com vista para o Palácio Nacional e o Oceano Atlântico. 5000m² de terreno, piscina aquecida, campo de padel, garagem para 4 carros.',
  '["Vista Palácio Mafra", "5000m² terreno", "Piscina aquecida", "Campo padel", "Garagem 4 carros", "Suite master piso 0", "Sala de jogos", "Churrasco exterior coberto"]',
  'Destaque',
  'active',
  '["Lifestyle Desporto", "Vista Atlântico", "Palácio Mafra 5min", "Família Activa"]',
  'linear-gradient(135deg, #3a1a2a 0%, #2a0c1a 100%)'
)

ON CONFLICT (id) DO UPDATE SET
  nome        = EXCLUDED.nome,
  preco       = EXCLUDED.preco,
  descricao   = EXCLUDED.descricao,
  features    = EXCLUDED.features,
  badge       = EXCLUDED.badge,
  updated_at  = NOW();
