// =============================================================================
// AGENCY GROUP — Agent Copilot Engine v1.0
// Module:  intelligence/copilot.ts
// Purpose: Generates deterministic, data-driven AI copilot suggestions for
//          agents and managers. Every suggestion references real data points —
//          no generic text, no randomness, no side effects.
//
// Design notes:
//   • Suggestions are generated by rule priority (first match wins per subject)
//   • Urgency sort: immediate > today > this_week > this_month
//   • ManagerBrief synthesises across leads, deals and opportunities
//   • All numeric values are NaN-safe (parsePTValue always returns a number)
//   • All user-facing strings are in Portuguese
// =============================================================================

import type { ScoredContact } from '../leadScoring'
import type { ScoredDeal } from '../dealScoring'
import type { Opportunity } from './opportunity'
import { parsePTValue } from '../../utils/format'

// ─── Types ────────────────────────────────────────────────────────────────────

export type CopilotUrgency = 'immediate' | 'today' | 'this_week' | 'this_month'

export interface CopilotSuggestion {
  /** Max 80 chars, action-oriented */
  headline: string
  /** 1 sentence referencing specific data */
  why: string
  /** Concrete step, max 120 chars */
  action: string
  urgency: CopilotUrgency
  /** 2–4 bullet data references */
  dataPoints: string[]
  confidence: 'high' | 'medium' | 'low'
}

export interface ManagerBrief {
  /** 1 sentence */
  biggestRisk: string
  /** Max 3 items */
  whereToIntervene: string[]
  /** 1 action */
  topPriority: string
  /** Euros — sum of at-risk commission from critical opportunities */
  revenueAtRisk: number
}

export interface AgentCopilotOutput {
  /** Max 3, sorted by urgency */
  topLeadSuggestions: CopilotSuggestion[]
  /** Max 3, sorted by urgency */
  topDealSuggestions: CopilotSuggestion[]
  managerBrief: ManagerBrief
}

// ─── Inline date helpers ──────────────────────────────────────────────────────

/** Days elapsed since a past date. Returns null on missing/invalid input. */
function daysSince(dateStr: string | null | undefined): number | null {
  if (!dateStr) return null
  const d = new Date(dateStr)
  if (isNaN(d.getTime())) return null
  return Math.floor((Date.now() - d.getTime()) / 86_400_000)
}

/** Days until a future date. Negative means past. Returns null on missing/invalid input. */
function daysUntil(dateStr: string | null | undefined): number | null {
  if (!dateStr) return null
  const d = new Date(dateStr)
  if (isNaN(d.getTime())) return null
  return Math.floor((d.getTime() - Date.now()) / 86_400_000)
}

// ─── Urgency sort order ───────────────────────────────────────────────────────

const URGENCY_ORDER: Record<CopilotUrgency, number> = {
  immediate:  0,
  today:      1,
  this_week:  2,
  this_month: 3,
}

function sortBySuggestionUrgency(suggestions: CopilotSuggestion[]): CopilotSuggestion[] {
  return [...suggestions].sort(
    (a, b) => URGENCY_ORDER[a.urgency] - URGENCY_ORDER[b.urgency],
  )
}

// ─── Lead suggestion generator ───────────────────────────────────────────────

/**
 * Generates a single copilot suggestion for a scored contact.
 * Returns null when no actionable condition matches.
 * Rule evaluation stops at the first match (priority order).
 */
export function generateLeadSuggestion(sc: ScoredContact): CopilotSuggestion | null {
  const { contact, scoring } = sc
  const name      = contact.name ?? 'Contacto sem nome'
  const score     = scoring.score
  const bandLabel = scoring.bandLabel
  const budgetMax = contact.budgetMax ?? 0
  const actCount  = contact.activities?.length ?? 0
  const tipos     = contact.tipos ?? []
  const zonas     = contact.zonas ?? []

  const followUpDays = daysUntil(contact.nextFollowUp)
  const lastDays     = daysSince(contact.lastContact) ?? 0

  // ── Rule 1: Overdue follow-up + score ≥ 60 ──────────────────────────────
  if (followUpDays !== null && followUpDays < 0 && score >= 60) {
    const daysOverdue = Math.abs(followUpDays)
    return {
      headline:   `Follow-up em atraso: ${name}`.slice(0, 80),
      why:        `Último contacto há ${lastDays}d e follow-up vencido — risco de perda`,
      action:     `Ligar ou enviar WhatsApp hoje com nova opção de ${tipos[0] ?? 'imóvel'} em ${zonas[0] ?? 'zona pretendida'}`.slice(0, 120),
      urgency:    'immediate',
      dataPoints: [
        `Score ${score} (${bandLabel})`,
        `Follow-up: ${daysOverdue}d em atraso`,
        `Budget: €${(budgetMax / 1_000).toFixed(0)}K`,
        `Último contacto: ${lastDays}d atrás`,
      ],
      confidence: 'high',
    }
  }

  // ── Rule 2: Band A or B + lastContact > 7d ──────────────────────────────
  if ((scoring.band === 'A' || scoring.band === 'B') && lastDays > 7) {
    const urgency: CopilotUrgency = scoring.band === 'A' ? 'today' : 'this_week'
    const conf = scoring.confidence === 'high' ? 'high' : 'medium'
    return {
      headline:   `Reactivar ${name} — ${bandLabel}`.slice(0, 80),
      why:        `Score ${score} sem contacto há ${lastDays}d`,
      action:     `Enviar selecção de ${tipos[0] ?? 'imóveis'} em ${zonas[0] ?? 'zona pretendida'} — mantém top of mind`.slice(0, 120),
      urgency,
      dataPoints: scoring.reasons.slice(0, 3),
      confidence: conf,
    }
  }

  // ── Rule 3: Score ≥ 75 + no activities ──────────────────────────────────
  if (score >= 75 && actCount === 0) {
    return {
      headline:   `Iniciar contacto com ${name}`.slice(0, 80),
      why:        `Score elevado (${score}) mas sem actividades registadas`,
      action:     'Agendar 1ª chamada — alta probabilidade de conversão pelo perfil'.slice(0, 120),
      urgency:    'today',
      dataPoints: scoring.reasons.slice(0, 3),
      confidence: 'medium',
    }
  }

  return null
}

// ─── Deal suggestion generator ────────────────────────────────────────────────

/**
 * Generates a single copilot suggestion for a scored deal.
 * Returns null when no actionable condition matches.
 * Rule evaluation stops at the first match (priority order).
 */
export function generateDealSuggestion(sd: ScoredDeal): CopilotSuggestion | null {
  const { deal, scoring } = sd
  const ref        = deal.ref ?? deal.id ?? 'Deal'
  const dealScore  = scoring.dealScore
  const dealHealth = scoring.dealHealth
  const fase       = deal.fase ?? ''
  const valor      = deal.valor ?? ''
  const closurePct = scoring.closurePct

  const highFlagCount = scoring.dealRiskFlags.filter(f => f.severity === 'high').length

  // ── Rule 1: CRITICO or EM_RISCO ─────────────────────────────────────────
  if (dealHealth === 'CRITICO' || dealHealth === 'EM_RISCO') {
    const urgency: CopilotUrgency = dealHealth === 'CRITICO' ? 'immediate' : 'today'
    const firstAction = scoring.dealAccelerationActions[0] ?? 'Rever deal urgentemente'
    return {
      headline:   `Deal ${ref} em risco — acção urgente`.slice(0, 80),
      why:        `Score ${dealScore} com ${highFlagCount} alerta(s) crítico(s)`,
      action:     firstAction.slice(0, 120),
      urgency,
      dataPoints: scoring.dealRiskFlags.slice(0, 3).map(f => f.label),
      confidence: 'high',
    }
  }

  // ── Rule 2: closureProbabilityBand ALTA + nearest date ≤ 14d ────────────
  if (scoring.closureProbabilityBand === 'ALTA') {
    const cpcvDays      = daysUntil(deal.cpcvDate)
    const escrituraDays = daysUntil(deal.escrituraDate)
    const validDays     = [cpcvDays, escrituraDays].filter((d): d is number => d !== null)
    const nearestDate   = validDays.length > 0 ? Math.min(...validDays) : null

    if (nearestDate !== null && nearestDate <= 14) {
      return {
        headline:   `${ref} a fechar em breve — preparar documentação`.slice(0, 80),
        why:        `Probabilidade de fecho ${closurePct}% com data em ≤14d`,
        action:     'Confirmar checklist e agendar notário — fecho iminente'.slice(0, 120),
        urgency:    'immediate',
        dataPoints: [
          `Fase: ${fase}`,
          `Valor: ${valor}`,
          `Score: ${dealScore}`,
          'Checklist: veja estado',
        ],
        confidence: 'high',
      }
    }
  }

  // ── Rule 3: MODERADO + no dates ──────────────────────────────────────────
  if (dealHealth === 'MODERADO' && !deal.cpcvDate && !deal.escrituraDate) {
    const firstAction = scoring.dealAccelerationActions[0] ?? 'Agendar reunião com todas as partes'
    return {
      headline:   `${ref} — definir próximas datas`.slice(0, 80),
      why:        `Deal sem CPCV nem escritura marcada em fase ${fase}`,
      action:     firstAction.slice(0, 120),
      urgency:    'this_week',
      dataPoints: scoring.reasons.slice(0, 3),
      confidence: 'medium',
    }
  }

  return null
}

// ─── Main copilot generator ───────────────────────────────────────────────────

/**
 * Generates a full AgentCopilotOutput from scored contacts, scored deals and
 * pre-detected opportunities. All suggestions are sorted by urgency and capped
 * at 3 items per category.
 */
export function generateCopilot(
  contacts: ScoredContact[],
  deals: ScoredDeal[],
  opportunities: Opportunity[],
): AgentCopilotOutput {

  // ── Lead suggestions ─────────────────────────────────────────────────────
  const leadSuggestions = sortBySuggestionUrgency(
    contacts
      .map(sc => generateLeadSuggestion(sc))
      .filter((s): s is CopilotSuggestion => s !== null),
  ).slice(0, 3)

  // ── Deal suggestions ─────────────────────────────────────────────────────
  const dealSuggestions = sortBySuggestionUrgency(
    deals
      .map(sd => generateDealSuggestion(sd))
      .filter((s): s is CopilotSuggestion => s !== null),
  ).slice(0, 3)

  // ── Manager brief ─────────────────────────────────────────────────────────

  // biggestRisk: first immediate deal suggestion → first critical opportunity → stable
  const firstImmediateDeal = dealSuggestions.find(s => s.urgency === 'immediate')
  const firstCriticalOpp   = opportunities.find(o => o.priority === 'critical')

  const biggestRisk: string = firstImmediateDeal
    ? firstImmediateDeal.headline
    : firstCriticalOpp
      ? firstCriticalOpp.reasoning[0]
      : 'Pipeline estável'

  // whereToIntervene: critical opps subjectName + immediate/today deal headlines (deduped, max 3)
  const criticalOppNames = opportunities
    .filter(o => o.priority === 'critical')
    .map(o => o.subjectName)

  const urgentDealHeadlines = dealSuggestions
    .filter(s => s.urgency === 'immediate' || s.urgency === 'today')
    .map(s => s.headline)

  const whereToIntervene = [
    ...criticalOppNames,
    ...urgentDealHeadlines,
  ]
    .filter((item, idx, arr) => arr.indexOf(item) === idx) // dedupe
    .slice(0, 3)

  // topPriority: first lead action, then first deal action, then fallback
  const topPriority =
    leadSuggestions[0]?.action ??
    dealSuggestions[0]?.action ??
    'Rever pipeline esta semana'

  // revenueAtRisk: sum of estimatedCommission on critical opportunities
  const revenueAtRisk = opportunities
    .filter(o => o.priority === 'critical')
    .reduce((sum, o) => sum + (o.estimatedCommission ?? 0), 0)

  return {
    topLeadSuggestions: leadSuggestions,
    topDealSuggestions: dealSuggestions,
    managerBrief: {
      biggestRisk,
      whereToIntervene,
      topPriority,
      revenueAtRisk,
    },
  }
}
